function add_subsystem(model_name, subsystem_name, position, color)
    path = [model_name '/' subsystem_name];
    add_block('simulink/Ports & Subsystems/Subsystem', path, ...
        'Position', position, ...
        'BackgroundColor', color, ...
        'ForegroundColor', 'black', ...
        'FontWeight', 'bold', ...
        'FontSize', '12', ...
        'ShowPortLabels', 'FromPortIcon');
    clear_subsystem(path);
end
