function build_tco_subsystem(path)
% TCO black box for the configured analysis horizon. The default case uses
% nominal cash flows (discount_rate_annual = 0).
%
% Two TCO boundaries are reported:
% 1. Facility TCO includes all facility electricity, including IT power.
% 2. Cooling TCO includes only cooling electricity plus cooling CAPEX,
%    fluid, maintenance, replacement, and disposal costs.

    add_in(path, 'AnnualFacilityEnergy_kWh', 1, [25 70 55 90]);
    add_in(path, 'AnnualCoolingEnergy_kWh', 2, [25 150 55 170]);

    add_block('simulink/Math Operations/Gain', ...
        [path '/Discounted Facility Electricity'], ...
        'Gain', 'electricity_discounted_price_factor_horizon', ...
        'Position', [120 45 285 95]);
    add_block('simulink/Math Operations/Gain', ...
        [path '/Discounted Cooling Electricity'], ...
        'Gain', 'electricity_discounted_price_factor_horizon', ...
        'Position', [120 125 285 175]);

    add_block('simulink/Math Operations/Gain', ...
        [path '/Nominal Facility Electricity'], ...
        'Gain', 'electricity_nominal_price_factor_horizon', ...
        'Position', [120 225 285 275]);
    add_block('simulink/Math Operations/Gain', ...
        [path '/Nominal Cooling Electricity'], ...
        'Gain', 'electricity_nominal_price_factor_horizon', ...
        'Position', [120 305 285 355]);

    add_block('simulink/Sources/Constant', [path '/Initial Cooling CAPEX'], ...
        'Value', 'initial_cooling_CAPEX', ...
        'Position', [355 405 475 435]);
    add_block('simulink/Sources/Constant', ...
        [path '/Discounted Nonenergy OPEX'], ...
        'Value', 'nonenergy_discounted_total_horizon', ...
        'Position', [355 455 500 485]);
    add_block('simulink/Sources/Constant', ...
        [path '/Nominal Nonenergy OPEX'], ...
        'Value', 'nonenergy_nominal_total_horizon', ...
        'Position', [355 505 500 535]);

    add_block('simulink/Math Operations/Sum', ...
        [path '/Discounted Facility TCO'], 'Inputs', '+++', ...
        'Position', [575 55 630 145]);
    add_block('simulink/Math Operations/Sum', ...
        [path '/Discounted Cooling TCO'], 'Inputs', '+++', ...
        'Position', [575 175 630 265]);
    add_block('simulink/Math Operations/Sum', ...
        [path '/Nominal Facility TCO'], 'Inputs', '+++', ...
        'Position', [575 295 630 385]);
    add_block('simulink/Math Operations/Sum', ...
        [path '/Nominal Cooling TCO'], 'Inputs', '+++', ...
        'Position', [575 415 630 505]);

    add_out(path, 'InitialCoolingCAPEX', 1, [755 40 785 60]);
    add_out(path, 'DiscountedFacilityTCO', 2, [755 100 785 120]);
    add_out(path, 'DiscountedCoolingTCO', 3, [755 160 785 180]);
    add_out(path, 'NominalFacilityTCO', 4, [755 220 785 240]);
    add_out(path, 'NominalCoolingTCO', 5, [755 280 785 300]);
    add_out(path, 'DiscountedFacilityElectricity', 6, [755 340 785 360]);
    add_out(path, 'DiscountedCoolingElectricity', 7, [755 400 785 420]);
    add_out(path, 'DiscountedNonenergyOPEX', 8, [755 460 785 480]);

    add_line(path, 'AnnualFacilityEnergy_kWh/1', ...
        'Discounted Facility Electricity/1');
    add_line(path, 'AnnualCoolingEnergy_kWh/1', ...
        'Discounted Cooling Electricity/1');
    add_line(path, 'AnnualFacilityEnergy_kWh/1', ...
        'Nominal Facility Electricity/1');
    add_line(path, 'AnnualCoolingEnergy_kWh/1', ...
        'Nominal Cooling Electricity/1');

    add_line(path, 'Discounted Facility Electricity/1', ...
        'Discounted Facility TCO/1');
    add_line(path, 'Initial Cooling CAPEX/1', ...
        'Discounted Facility TCO/2');
    add_line(path, 'Discounted Nonenergy OPEX/1', ...
        'Discounted Facility TCO/3');

    add_line(path, 'Discounted Cooling Electricity/1', ...
        'Discounted Cooling TCO/1');
    add_line(path, 'Initial Cooling CAPEX/1', ...
        'Discounted Cooling TCO/2');
    add_line(path, 'Discounted Nonenergy OPEX/1', ...
        'Discounted Cooling TCO/3');

    add_line(path, 'Nominal Facility Electricity/1', ...
        'Nominal Facility TCO/1');
    add_line(path, 'Initial Cooling CAPEX/1', ...
        'Nominal Facility TCO/2');
    add_line(path, 'Nominal Nonenergy OPEX/1', ...
        'Nominal Facility TCO/3');

    add_line(path, 'Nominal Cooling Electricity/1', ...
        'Nominal Cooling TCO/1');
    add_line(path, 'Initial Cooling CAPEX/1', ...
        'Nominal Cooling TCO/2');
    add_line(path, 'Nominal Nonenergy OPEX/1', ...
        'Nominal Cooling TCO/3');

    add_line(path, 'Initial Cooling CAPEX/1', 'InitialCoolingCAPEX/1');
    add_line(path, 'Discounted Facility TCO/1', ...
        'DiscountedFacilityTCO/1');
    add_line(path, 'Discounted Cooling TCO/1', ...
        'DiscountedCoolingTCO/1');
    add_line(path, 'Nominal Facility TCO/1', 'NominalFacilityTCO/1');
    add_line(path, 'Nominal Cooling TCO/1', 'NominalCoolingTCO/1');
    add_line(path, 'Discounted Facility Electricity/1', ...
        'DiscountedFacilityElectricity/1');
    add_line(path, 'Discounted Cooling Electricity/1', ...
        'DiscountedCoolingElectricity/1');
    add_line(path, 'Discounted Nonenergy OPEX/1', ...
        'DiscountedNonenergyOPEX/1');
end
