function build_inputs_subsystem(path)
%BUILD_INPUTS_SUBSYSTEM Central user-input cabinet for the native model.
%
% The nested Fluid Properties and Operating Scenario sections retain their
% existing live signals. Facility hypotheses are collected here as editable
% constants and the facility power/U values are passed into the rack model.

    add_subsystem(path, 'Fluid Properties', [30 45 300 300], 'lightBlue');
    build_fluid_properties_subsystem([path '/Fluid Properties']);
    add_subsystem(path, 'Operating Scenario', [30 330 300 565], 'lightBlue');
    build_scenario_subsystem([path '/Operating Scenario']);

    add_subsystem(path, 'Facility Hypotheses', [350 45 650 420], 'yellow');
    h = [path '/Facility Hypotheses'];
    add_block('simulink/Sources/Constant', [h '/Facility IT Power kW'], ...
        'Value', num2str(evalin('base','facility_design_IT_power_kW'),15), ...
        'Position', [35 45 155 75]);
    add_block('simulink/Math Operations/Divide', [h '/Facility U Calculation'], ...
        'Position', [175 65 225 125]);
    add_block('simulink/Sources/Constant', [h '/Rack U'], ...
        'Value', num2str(evalin('base','rack_U'),15), ...
        'Position', [35 165 155 195]);
    add_block('simulink/Sources/Constant', [h '/Average kW per U'], ...
        'Value', num2str(evalin('base','kW_per_U'),15), ...
        'Position', [35 225 155 255]);
    add_block('simulink/Sources/Constant', [h '/Coldplates per U'], ...
        'Value', num2str(evalin('base','coldplates_per_U'),15), ...
        'Position', [35 285 155 315]);
    add_block('simulink/Ports & Subsystems/Out1', [h '/FacilityITPower_kW'], ...
        'Port', '1', 'Position', [245 50 275 70]);
    add_block('simulink/Ports & Subsystems/Out1', [h '/FacilityU'], ...
        'Port', '2', 'Position', [245 110 275 130]);
    add_block('simulink/Ports & Subsystems/Out1', [h '/RackU'], ...
        'Port', '3', 'Position', [245 170 275 190]);
    add_block('simulink/Ports & Subsystems/Out1', [h '/ColdplatesPerU'], ...
        'Port', '4', 'Position', [245 230 275 250]);
    add_block('simulink/Sinks/Display', [h '/Calculated Facility U Display'], ...
        'Position', [245 145 365 180]);
    add_line(h, 'Facility IT Power kW/1', 'FacilityITPower_kW/1');
    add_line(h, 'Facility IT Power kW/1', 'Facility U Calculation/1');
    add_line(h, 'Average kW per U/1', 'Facility U Calculation/2');
    add_line(h, 'Facility U Calculation/1', 'FacilityU/1');
    add_line(h, 'Facility U Calculation/1', 'Calculated Facility U Display/1');
    add_line(h, 'Rack U/1', 'RackU/1');
    add_line(h, 'Coldplates per U/1', 'ColdplatesPerU/1');


    add_subsystem(path, 'Hydraulic Hypotheses', [350 440 650 760], 'yellow');
    q = [path '/Hydraulic Hypotheses'];
    add_in(q, 'RackUInput', 1, [5 30 35 50]);
    add_in(q, 'ColdplatesPerUInput', 2, [5 75 35 95]);
    q_names = {'Internal Fixed Pipe Length m','Internal Pipe Diameter m', ...
        'Internal Pipe Roughness m','Internal Fittings K','Coldplate dP Pa', ...
        'Coldplates per U','External Fixed Pipe Length m','External U per Rack', ...
        'Additional External Length per Rack m','External Pipe Diameter m', ...
        'External Pipe Roughness m','External Fittings K'};
    q_values = {'internal_fixed_pipe_length_m','internal_pipe_diameter_m', ...
        'internal_pipe_roughness_m','internal_fittings_loss_coefficient', ...
        'coldplate_pressure_drop_Pa','coldplates_per_U', ...
        'external_fixed_pipe_length_m','rack_U', ...
        'additional_external_pipe_length_per_rack_m','external_pipe_diameter_m', ...
        'external_pipe_roughness_m','external_fittings_loss_coefficient'};
    q_outputs = {'Internal Pipe Length to Loop m','Internal Diameter to Loop m', ...
        'Internal Roughness to Loop m','Internal Fittings K to Loop', ...
        'Coldplate Pressure Drop to Loop Pa','Coldplates per U to Loop', ...
        'External Pipe Length Base to Loop m','External U per Rack to Loop', ...
        'Additional External Length to Loop m','External Diameter to Loop m', ...
        'External Roughness to Loop m','External Fittings K to Loop'};
    for i = 1:numel(q_names)
        y = 35 + (i-1)*45;
        if i ~= 6 && i ~= 8
            add_block('simulink/Sources/Constant', [q '/' q_names{i}], ...
                'Value', num2str(evalin('base',q_values{i}),15), ...
                'Position', [45 y 165 y+25]);
        end
        add_block('simulink/Ports & Subsystems/Out1', [q '/' q_outputs{i}], ...
            'Port', num2str(i), 'Position', [245 y+3 275 y+23]);
        if i == 6
            add_line(q, 'ColdplatesPerUInput/1', [q_outputs{i} '/1']);
        elseif i == 8
            add_line(q, 'RackUInput/1', [q_outputs{i} '/1']);
        else
            add_line(q, [q_names{i} '/1'], [q_outputs{i} '/1']);
        end
    end

    add_subsystem(path, 'IT Load and Rack Sizing', [30 600 300 820], 'lightGreen');
    build_it_racks_subsystem([path '/IT Load and Rack Sizing']);
    add_line(path, 'Operating Scenario/1', 'IT Load and Rack Sizing/1');
    add_line(path, 'Facility Hypotheses/1', 'IT Load and Rack Sizing/2');
    add_line(path, 'Facility Hypotheses/2', 'IT Load and Rack Sizing/3');

    add_subsystem(path, 'Cost Hypotheses', [680 440 980 700], 'yellow');
    c = [path '/Cost Hypotheses'];
    cost_names = {'Annual Top-up Quantity L_per_year','Fluid Price $_per_L', ...
        'Fluid Renewal Lifetime years','Annual Maintenance Cost $_per_year'};
    cost_values = {'annual_makeup_volume_L','fluid_unit_price_year1_per_L', ...
        'full_replacement_interval_years','annual_maintenance_monitoring_year1'};
    for i = 1:numel(cost_names)
        y = 45 + (i-1)*60;
        add_block('simulink/Sources/Constant', [c '/' cost_names{i}], ...
            'Value', num2str(evalin('base',cost_values{i}),15), ...
            'Position', [25 y 170 y+30]);
        add_block('simulink/Ports & Subsystems/Out1', [c '/Cost Input ' num2str(i)], ...
            'Port', num2str(i), 'Position', [245 y+5 275 y+25]);
        add_line(c, [cost_names{i} '/1'], ['Cost Input ' num2str(i) '/1']);
    end

    add_subsystem(path, 'Tower Hypotheses', [1000 440 1300 980], 'cyan');
    t = [path '/Tower Hypotheses'];
    tower_names = {'Tower Design Heat kW','Tower Design Flow m3 per h', ...
        'Tower Minimum Flow Ratio','Tower Design Range K','Tower Design Wet Bulb C', ...
        'Tower Design Approach K','Tower Load Sensitivity K','Tower Low Flow Sensitivity K', ...
        'Tower Ambient Power Sensitivity per K','Tower Fan Design kW','Tower Spray Pump Design kW'};
    tower_values = {'tower_design_heat_kW','tower_design_flow_m3h', ...
        'tower_minimum_flow_ratio','tower_design_range_K','tower_design_wet_bulb_C', ...
        'tower_design_approach_K','tower_approach_load_sensitivity_K', ...
        'tower_approach_low_flow_sensitivity_K','tower_ambient_power_sensitivity_per_K', ...
        'tower_fan_design_kW','tower_spray_pump_design_kW'};
    for i = 1:numel(tower_names)
        y = 35 + (i-1)*45;
        add_block('simulink/Sources/Constant', [t '/' tower_names{i}], ...
            'Value', num2str(evalin('base',tower_values{i}),15), ...
            'Position', [25 y 175 y+25]);
        add_block('simulink/Ports & Subsystems/Out1', [t '/Tower Input ' num2str(i)], ...
            'Port', num2str(i), 'Position', [245 y+3 275 y+23]);
        add_line(t, [tower_names{i} '/1'], ['Tower Input ' num2str(i) '/1']);
    end

    % Inputs subsystem interface: scenario, fluid, then facility hypotheses.
    names = {'LoadFraction','AmbientWetBulbC','ElectricityPrice','OperatingMonths', ...
        'InternalCp_J_kgK','InternalDensity_kg_m3','InternalViscosity_Pa_s', ...
        'InternalConductivity_W_mK','ExternalCp_J_kgK','ExternalDensity_kg_m3', ...
        'ExternalViscosity_Pa_s','ExternalConductivity_W_mK','FacilityITPower_kW','FacilityU', ...
        'InternalFixedPipeLength_m','InternalPipeDiameter_m','InternalPipeRoughness_m', ...
        'InternalFittingsK','ColdplatePressureDrop_Pa','ColdplatesPerU', ...
        'ExternalFixedPipeLength_m','ExternalUPerRack','AdditionalLengthPerRack_m', ...
        'ExternalPipeDiameter_m','ExternalPipeRoughness_m','ExternalFittingsK', ...
        'ITPower_kW','HeatToLiquid_kW','FacilityU_Used', ...
        'AnnualTopUpQuantity_L_per_year','FluidPrice_$_per_L', ...
        'FluidRenewalLifetime_years','AnnualMaintenanceCost_$_per_year', ...
        'TowerDesignHeat_kW','TowerDesignFlow_m3h','TowerMinimumFlowRatio', ...
        'TowerDesignRange_K','TowerDesignWetBulb_C','TowerDesignApproach_K', ...
        'TowerLoadSensitivity_K','TowerLowFlowSensitivity_K', ...
        'TowerAmbientPowerSensitivity_per_K','TowerFanDesign_kW','TowerSprayPumpDesign_kW'};
    positions = [760 55; 760 90; 760 125; 760 160; 760 220; 760 255; ...
        760 290; 760 325; 760 385; 760 420; 760 455; 760 490; 760 550; 760 585; ...
        760 620; 760 655; 760 690; 760 725; 760 760; 760 795; ...
        760 830; 760 865; 760 900; 760 935; 760 970; 760 1005; ...
        760 1040; 760 1075; 760 1110; 760 1145; 760 1180; 760 1215; 760 1250; ...
        760 1285; 760 1320; 760 1355; 760 1390; 760 1425; 760 1460; ...
        760 1495; 760 1530; 760 1565; 760 1600; 760 1635];
    for i = 1:numel(names)
        add_out(path, names{i}, i, [positions(i,1) positions(i,2) positions(i,1)+30 positions(i,2)+20]);
    end

    % Scenario outputs 1:4.
    for i = 1:4
        add_line(path, ['Operating Scenario/' num2str(i)], [names{i} '/1']);
    end
    % Fluid outputs 1:8 map to Inputs outputs 5:12.
    for i = 1:8
        add_line(path, ['Fluid Properties/' num2str(i)], [names{i+4} '/1']);
    end
    add_line(path, 'Facility Hypotheses/1', 'FacilityITPower_kW/1');
    add_line(path, 'Facility Hypotheses/2', 'FacilityU/1');
    add_line(path, 'Facility Hypotheses/3', 'Hydraulic Hypotheses/1');
    add_line(path, 'Facility Hypotheses/4', 'Hydraulic Hypotheses/2');
    for i = 1:12
        add_line(path, ['Hydraulic Hypotheses/' num2str(i)], [names{i+14} '/1']);
    end
    add_line(path, 'IT Load and Rack Sizing/1', 'ITPower_kW/1');
    add_line(path, 'IT Load and Rack Sizing/2', 'HeatToLiquid_kW/1');
    add_line(path, 'IT Load and Rack Sizing/3', 'FacilityU_Used/1');
    for i = 1:4
        add_line(path, ['Cost Hypotheses/' num2str(i)], [names{i+29} '/1']);
    end
    for i = 1:11
        add_line(path, ['Tower Hypotheses/' num2str(i)], [names{i+33} '/1']);
    end


    Simulink.Annotation(path, sprintf([ ...
        'INPUTS\n' ...
        'Edit the constants inside Fluid Properties, Operating Scenario, ' ...
        'Facility Hypotheses, and Hydraulic Hypotheses.']));
end
