function build_simscape_reference_subsystem(path)
%BUILD_SIMSCAPE_REFERENCE_SUBSYSTEM Optional physical-network scaffold.
% This reference path is intentionally parallel to the calibrated signal
% model; it does not alter existing outputs until its fluid/pump map is
% validated against measured equipment data.
    add_block('simulink/Ports & Subsystems/Subsystem', path, ...
        'Position', [1880 360 2160 520]);
    clear_subsystem(path);
    try
        add_block('fl_lib/Isothermal Liquid/Elements/Pipe (IL)', ...
            [path '/Internal Pipe Reference'], 'Position', [140 100 250 160]);
        add_block('fl_lib/Isothermal Liquid/Elements/Pipe (IL)', ...
            [path '/External Pipe Reference'], 'Position', [140 260 250 320]);
        Simulink.Annotation(path, sprintf([ ...
            'SIMSCAPE FLUIDS REFERENCE (OPTIONAL)\n' ...
            'Parallel scaffold only; the calibrated signal model remains active.\n' ...
            'Configure Pipe (IL) geometry and connect pump/reservoir maps here.']));
    catch exception
        Simulink.Annotation(path, sprintf([ ...
            'SIMSCAPE FLUIDS REFERENCE\n' ...
            'Optional blocks unavailable in this release: %s'], exception.message));
    end
end
