function build_facility_loop_subsystem(path)
% Reduced-order external PG25 facility-loop black box.
    add_in(path, 'HeatFromCDU_kW', 1, [25 70 55 90]);
    add_in(path, 'TowerSupply_C', 2, [25 230 55 250]);

    flow_expr = [ ...
        'u*1000*3600/' ...
        '(rhoCp_external_effective_J_m3K*external_target_deltaT_K)'];
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/Required Delivered Flow'], ...
        'Expr', flow_expr, 'Position', [120 45 290 95]);

    pump_expr = [ ...
        '(external_reference_pressure_drop_Pa*' ...
        '((u*1000/(rhoCp_external_effective_J_m3K*external_target_deltaT_K)/' ...
        'external_pump_flow_capacity_factor)/Vdot_external_reference_m3s)^2*' ...
        '(rho_external_effective_kg_m3/rho_external_kg_m3)*' ...
        '(mu_external_Pas/mu_external_reference_Pas)^mu_pressure_exponent)*' ...
        '(u*1000/(rhoCp_external_effective_J_m3K*external_target_deltaT_K)/' ...
        'external_pump_flow_capacity_factor)/' ...
        '(external_pump_efficiency_effective*1000)'];
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/External Pump Correlation'], ...
        'Expr', pump_expr, 'Position', [120 120 330 180]);

    add_block('simulink/Math Operations/Sum', ...
        [path '/Heat to Tower kW'], 'Inputs', '++', ...
        'Position', [390 105 440 170]);

    add_block('simulink/Sources/Constant', [path '/External DeltaT K'], ...
        'Value', 'external_target_deltaT_K', ...
        'Position', [120 250 220 280]);
    add_block('simulink/Math Operations/Sum', ...
        [path '/External Return C'], 'Inputs', '++', ...
        'Position', [290 220 340 285]);

    add_out(path, 'HeatToTower_kW', 1, [700 125 730 145]);
    add_out(path, 'ExternalFlow_m3h', 2, [700 55 730 75]);
    add_out(path, 'ExternalPump_kW', 3, [700 180 730 200]);
    add_out(path, 'ExternalReturn_C', 4, [700 245 730 265]);
    add_out(path, 'LoopDeltaT_K', 5, [700 315 730 335]);

    add_line(path, 'HeatFromCDU_kW/1', 'Required Delivered Flow/1');
    add_line(path, 'Required Delivered Flow/1', 'ExternalFlow_m3h/1');
    add_line(path, 'HeatFromCDU_kW/1', 'External Pump Correlation/1');
    add_line(path, 'External Pump Correlation/1', 'ExternalPump_kW/1');
    add_line(path, 'HeatFromCDU_kW/1', 'Heat to Tower kW/1');
    add_line(path, 'External Pump Correlation/1', 'Heat to Tower kW/2');
    add_line(path, 'Heat to Tower kW/1', 'HeatToTower_kW/1');

    add_line(path, 'TowerSupply_C/1', 'External Return C/1');
    add_line(path, 'External DeltaT K/1', 'External Return C/2');
    add_line(path, 'External Return C/1', 'ExternalReturn_C/1');
    add_line(path, 'External DeltaT K/1', 'LoopDeltaT_K/1');
end
