function build_cdu_subsystem(path)
% Reduced-order CDU/internal-loop black box.
    add_in(path, 'HeatFromRacks_kW', 1, [25 70 55 90]);
    add_in(path, 'ExternalSupply_C', 2, [25 230 55 250]);

    flow_expr = [ ...
        'u*1000*3600/' ...
        '(rhoCp_internal_effective_J_m3K*internal_target_deltaT_K)'];
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/Required Delivered Flow'], ...
        'Expr', flow_expr, 'Position', [120 45 290 95]);

    pump_expr = [ ...
        '(internal_reference_pressure_drop_Pa*' ...
        '((u*1000/(rhoCp_internal_effective_J_m3K*internal_target_deltaT_K)/' ...
        'internal_pump_flow_capacity_factor)/Vdot_internal_reference_m3s)^2*' ...
        '(rho_internal_effective_kg_m3/rho_internal_kg_m3)*' ...
        '(mu_internal_Pas/mu_internal_reference_Pas)^mu_pressure_exponent)*' ...
        '(u*1000/(rhoCp_internal_effective_J_m3K*internal_target_deltaT_K)/' ...
        'internal_pump_flow_capacity_factor)/' ...
        '(internal_pump_efficiency_effective*1000)'];
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/Internal Pump Correlation'], ...
        'Expr', pump_expr, 'Position', [120 120 330 180]);

    add_block('simulink/Math Operations/Sum', ...
        [path '/Heat to External kW'], 'Inputs', '++', ...
        'Position', [390 105 440 170]);

    add_block('simulink/Sources/Constant', [path '/HX Approach K'], ...
        'Value', 'HX_approach_K', 'Position', [120 220 200 250]);
    add_block('simulink/Sources/Constant', [path '/Internal DeltaT K'], ...
        'Value', 'internal_target_deltaT_K', ...
        'Position', [120 270 215 300]);
    add_block('simulink/Math Operations/Sum', ...
        [path '/Internal Return C'], 'Inputs', '+++', ...
        'Position', [280 215 330 300]);

    add_block('simulink/Signal Routing/Mux', [path '/Chip Inputs'], ...
        'Inputs', '2', 'Position', [390 235 410 290]);
    chip_expr = [ ...
        'u(1)+HX_approach_K+0.5*internal_target_deltaT_K+' ...
        'u(2)*1000/total_coldplate_paths*' ...
        'Rth_chip_to_coolant_effective_K_W'];
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/Chip Temperature Correlation'], ...
        'Expr', chip_expr, 'Position', [465 225 650 295]);

    add_out(path, 'HeatToExternal_kW', 1, [735 125 765 145]);
    add_out(path, 'InternalFlow_m3h', 2, [735 55 765 75]);
    add_out(path, 'InternalPump_kW', 3, [735 180 765 200]);
    add_out(path, 'InternalReturn_C', 4, [735 245 765 265]);
    add_out(path, 'ChipTemperature_C', 5, [735 315 765 335]);

    add_line(path, 'HeatFromRacks_kW/1', 'Required Delivered Flow/1');
    add_line(path, 'Required Delivered Flow/1', 'InternalFlow_m3h/1');
    add_line(path, 'HeatFromRacks_kW/1', 'Internal Pump Correlation/1');
    add_line(path, 'Internal Pump Correlation/1', 'InternalPump_kW/1');
    add_line(path, 'HeatFromRacks_kW/1', 'Heat to External kW/1');
    add_line(path, 'Internal Pump Correlation/1', 'Heat to External kW/2');
    add_line(path, 'Heat to External kW/1', 'HeatToExternal_kW/1');

    add_line(path, 'ExternalSupply_C/1', 'Internal Return C/1');
    add_line(path, 'HX Approach K/1', 'Internal Return C/2');
    add_line(path, 'Internal DeltaT K/1', 'Internal Return C/3');
    add_line(path, 'Internal Return C/1', 'InternalReturn_C/1');

    add_line(path, 'ExternalSupply_C/1', 'Chip Inputs/1');
    add_line(path, 'HeatFromRacks_kW/1', 'Chip Inputs/2');
    add_line(path, 'Chip Inputs/1', 'Chip Temperature Correlation/1');
    add_line(path, 'Chip Temperature Correlation/1', 'ChipTemperature_C/1');
end
