function build_inputs_subsystem(path)
%BUILD_INPUTS_SUBSYSTEM Central user-input cabinet for the native model.
%
% The nested Fluid Properties and Operating Scenario sections retain their
% existing live signals. Facility hypotheses are collected here as editable
% constants and the facility power/U values are passed into the rack model.

    add_subsystem(path, 'Fluid Properties', [30 45 300 300], 'lightBlue');
    build_fluid_properties_subsystem([path '/Fluid Properties']);
    add_subsystem(path, 'Operating Scenario', [30 330 300 565], 'lightBlue');
    build_scenario_subsystem([path '/Operating Scenario']);

    add_subsystem(path, 'Facility Hypotheses', [350 45 650 420], 'yellow');
    h = [path '/Facility Hypotheses'];
    add_block('simulink/Sources/Constant', [h '/Facility IT Power kW'], ...
        'Value', num2str(evalin('base','facility_design_IT_power_kW'),15), ...
        'Position', [35 45 155 75]);
    add_block('simulink/Sources/Constant', [h '/Facility U'], ...
        'Value', num2str(evalin('base','facility_total_U'),15), ...
        'Position', [35 105 155 135]);
    add_block('simulink/Sources/Constant', [h '/Rack U'], ...
        'Value', num2str(evalin('base','rack_U'),15), ...
        'Position', [35 165 155 195]);
    add_block('simulink/Sources/Constant', [h '/kW per U'], ...
        'Value', num2str(evalin('base','kW_per_U'),15), ...
        'Position', [35 225 155 255]);
    add_block('simulink/Sources/Constant', [h '/Coldplates per U'], ...
        'Value', num2str(evalin('base','coldplates_per_U'),15), ...
        'Position', [35 285 155 315]);
    add_block('simulink/Ports & Subsystems/Out1', [h '/FacilityITPower_kW'], ...
        'Port', '1', 'Position', [245 50 275 70]);
    add_block('simulink/Ports & Subsystems/Out1', [h '/FacilityU'], ...
        'Port', '2', 'Position', [245 110 275 130]);
    add_line(h, 'Facility IT Power kW/1', 'FacilityITPower_kW/1');
    add_line(h, 'Facility U/1', 'FacilityU/1');

    add_subsystem(path, 'Hydraulic Hypotheses', [350 440 650 760], 'yellow');
    q = [path '/Hydraulic Hypotheses'];
    q_names = {'Internal Fixed Pipe Length m','Internal Pipe Diameter m', ...
        'Internal Pipe Roughness m','Internal Fittings K','Coldplate dP Pa', ...
        'Coldplates per U','External Fixed Pipe Length m','External U per Rack', ...
        'Additional External Length per Rack m','External Pipe Diameter m', ...
        'External Pipe Roughness m','External Fittings K'};
    q_values = {'internal_fixed_pipe_length_m','internal_pipe_diameter_m', ...
        'internal_pipe_roughness_m','internal_fittings_loss_coefficient', ...
        'coldplate_pressure_drop_Pa','coldplates_per_U', ...
        'external_fixed_pipe_length_m','rack_U', ...
        'additional_external_pipe_length_per_rack_m','external_pipe_diameter_m', ...
        'external_pipe_roughness_m','external_fittings_loss_coefficient'};
    for i = 1:numel(q_names)
        y = 35 + (i-1)*45;
        add_block('simulink/Sources/Constant', [q '/' q_names{i}], ...
            'Value', num2str(evalin('base',q_values{i}),15), ...
            'Position', [25 y 145 y+25]);
        add_block('simulink/Ports & Subsystems/Out1', [q '/Output ' num2str(i)], ...
            'Port', num2str(i), 'Position', [245 y+3 275 y+23]);
        add_line(q, [q_names{i} '/1'], ['Output ' num2str(i) '/1']);
    end

    add_subsystem(path, 'IT Load and Rack Sizing', [30 600 300 820], 'lightGreen');
    build_it_racks_subsystem([path '/IT Load and Rack Sizing']);
    add_line(path, 'Operating Scenario/1', 'IT Load and Rack Sizing/1');
    add_line(path, 'Facility Hypotheses/1', 'IT Load and Rack Sizing/2');
    add_line(path, 'Facility Hypotheses/2', 'IT Load and Rack Sizing/3');

    % Inputs subsystem interface: scenario, fluid, then facility hypotheses.
    names = {'LoadFraction','AmbientWetBulbC','ElectricityPrice','OperatingMonths', ...
        'InternalCp_J_kgK','InternalDensity_kg_m3','InternalViscosity_Pa_s', ...
        'InternalConductivity_W_mK','ExternalCp_J_kgK','ExternalDensity_kg_m3', ...
        'ExternalViscosity_Pa_s','ExternalConductivity_W_mK','FacilityITPower_kW','FacilityU', ...
        'InternalFixedPipeLength_m','InternalPipeDiameter_m','InternalPipeRoughness_m', ...
        'InternalFittingsK','ColdplatePressureDrop_Pa','ColdplatesPerU', ...
        'ExternalFixedPipeLength_m','ExternalUPerRack','AdditionalLengthPerRack_m', ...
        'ExternalPipeDiameter_m','ExternalPipeRoughness_m','ExternalFittingsK', ...
        'ITPower_kW','HeatToLiquid_kW','FacilityU_Used'};
    positions = [760 55; 760 90; 760 125; 760 160; 760 220; 760 255; ...
        760 290; 760 325; 760 385; 760 420; 760 455; 760 490; 760 550; 760 585; ...
        760 620; 760 655; 760 690; 760 725; 760 760; 760 795; ...
        760 830; 760 865; 760 900; 760 935; 760 970; 760 1005; ...
        760 1040; 760 1075; 760 1110];
    for i = 1:numel(names)
        add_out(path, names{i}, i, [positions(i,1) positions(i,2) positions(i,1)+30 positions(i,2)+20]);
    end

    % Scenario outputs 1:4.
    for i = 1:4
        add_line(path, ['Operating Scenario/' num2str(i)], [names{i} '/1']);
    end
    % Fluid outputs 1:8 map to Inputs outputs 5:12.
    for i = 1:8
        add_line(path, ['Fluid Properties/' num2str(i)], [names{i+4} '/1']);
    end
    add_line(path, 'Facility Hypotheses/1', 'FacilityITPower_kW/1');
    add_line(path, 'Facility Hypotheses/2', 'FacilityU/1');
    for i = 1:12
        add_line(path, ['Hydraulic Hypotheses/' num2str(i)], [names{i+14} '/1']);
    end
    add_line(path, 'IT Load and Rack Sizing/1', 'ITPower_kW/1');
    add_line(path, 'IT Load and Rack Sizing/2', 'HeatToLiquid_kW/1');
    add_line(path, 'IT Load and Rack Sizing/3', 'FacilityU_Used/1');

    Simulink.Annotation(path, sprintf([ ...
        'INPUTS\n' ...
        'Edit the constants inside Fluid Properties, Operating Scenario, ' ...
        'Facility Hypotheses, and Hydraulic Hypotheses.']));
end
