function build_aeration_subsystem(path)
%BUILD_AERATION_SUBSYSTEM Calculate free-gas mixture and derating effects.
%
% Inputs are clean-liquid properties from the Fluid Properties subsystem.
% The two air-volume-fraction Constant blocks are tunable during simulation
% using Dashboard Sliders. The outputs are explicit signals consumed by the
% internal and external hydraulic black boxes.

    alpha_i = evalin('base', 'air_void_fraction_internal');
    alpha_e = evalin('base', 'air_void_fraction_external');

    add_in(path, 'InternalCp_J_kgK', 1, [25 50 55 70]);
    add_in(path, 'InternalDensity_kg_m3', 2, [25 105 55 125]);
    add_in(path, 'InternalConductivity_W_mK', 3, [25 160 55 180]);
    add_in(path, 'ExternalCp_J_kgK', 4, [25 330 55 350]);
    add_in(path, 'ExternalDensity_kg_m3', 5, [25 385 55 405]);

    add_block('simulink/Sources/Constant', ...
        [path '/Internal Air Volume Fraction'], ...
        'Value', num2str(alpha_i, 15), 'Position', [95 215 185 245]);
    add_block('simulink/Sources/Constant', ...
        [path '/External Air Volume Fraction'], ...
        'Value', num2str(alpha_e, 15), 'Position', [95 440 185 470]);

    % Internal effective volumetric heat capacity.
    add_block('simulink/Signal Routing/Mux', [path '/Internal RhoCp Inputs'], ...
        'Inputs', '3', 'Position', [235 40 255 130]);
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/Internal Effective RhoCp'], ...
        'Expr', '(1-u(1))*u(2)*u(3)+u(1)*rho_air_kg_m3*cp_air_J_kgK', ...
        'Position', [305 55 500 105]);

    % Internal mixture density.
    add_block('simulink/Signal Routing/Mux', [path '/Internal Density Inputs'], ...
        'Inputs', '2', 'Position', [235 130 255 190]);
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/Internal Effective Density'], ...
        'Expr', '(1-u(1))*u(2)+u(1)*rho_air_kg_m3', ...
        'Position', [305 135 500 180]);

    % Internal pump derating factors.
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/Internal Flow Capacity Factor'], ...
        'Expr', ['max(minimum_pump_flow_capacity_factor,' ...
                 '1-internal_flow_derating_coefficient*u)'], ...
        'Position', [305 205 500 245]);
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/Internal Efficiency Factor'], ...
        'Expr', ['max(minimum_pump_efficiency_fraction,' ...
                 '1-internal_efficiency_derating_coefficient*u)'], ...
        'Position', [305 260 500 300]);

    % Conductivity-sensitive clean Rth followed by aeration penalty.
    add_block('simulink/Signal Routing/Mux', [path '/Rth Inputs'], ...
        'Inputs', '2', 'Position', [235 205 255 275]);
    rth_expr = [ ...
        'Rth_chip_to_coolant_K_W*' ...
        '((1-coldplate_fluid_side_resistance_fraction)+' ...
        'coldplate_fluid_side_resistance_fraction*' ...
        'k_internal_reference_W_mK/max(u(2),1e-9))*' ...
        '(1+Rth_aeration_sensitivity*u(1))'];
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/Effective Coldplate Rth'], ...
        'Expr', rth_expr, 'Position', [555 220 780 275]);

    % External mixture and pump derating.
    add_block('simulink/Signal Routing/Mux', [path '/External RhoCp Inputs'], ...
        'Inputs', '3', 'Position', [235 325 255 415]);
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/External Effective RhoCp'], ...
        'Expr', '(1-u(1))*u(2)*u(3)+u(1)*rho_air_kg_m3*cp_air_J_kgK', ...
        'Position', [305 335 500 385]);

    add_block('simulink/Signal Routing/Mux', [path '/External Density Inputs'], ...
        'Inputs', '2', 'Position', [235 405 255 465]);
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/External Effective Density'], ...
        'Expr', '(1-u(1))*u(2)+u(1)*rho_air_kg_m3', ...
        'Position', [305 410 500 455]);

    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/External Flow Capacity Factor'], ...
        'Expr', ['max(minimum_pump_flow_capacity_factor,' ...
                 '1-external_flow_derating_coefficient*u)'], ...
        'Position', [305 485 500 525]);
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/External Efficiency Factor'], ...
        'Expr', ['max(minimum_pump_efficiency_fraction,' ...
                 '1-external_efficiency_derating_coefficient*u)'], ...
        'Position', [305 540 500 580]);

    % Interface outputs.
    add_out(path, 'InternalAirFraction', 1, [980 30 1010 50]);
    add_out(path, 'ExternalAirFraction', 2, [980 75 1010 95]);
    add_out(path, 'InternalRhoCp_J_m3K', 3, [980 120 1010 140]);
    add_out(path, 'InternalDensity_kg_m3', 4, [980 165 1010 185]);
    add_out(path, 'InternalFlowCapacityFactor', 5, [980 210 1010 230]);
    add_out(path, 'InternalEfficiencyFactor', 6, [980 255 1010 275]);
    add_out(path, 'EffectiveRth_K_W', 7, [980 300 1010 320]);
    add_out(path, 'ExternalRhoCp_J_m3K', 8, [980 390 1010 410]);
    add_out(path, 'ExternalDensity_kg_m3', 9, [980 435 1010 455]);
    add_out(path, 'ExternalFlowCapacityFactor', 10, [980 480 1010 500]);
    add_out(path, 'ExternalEfficiencyFactor', 11, [980 525 1010 545]);

    % Live and final-value displays.
    display_specs = {
        'Internal Air Display',       [815 25 920 55];
        'External Air Display',       [815 70 920 100];
        'Internal RhoCp Display',     [815 115 920 145];
        'Internal Density Display',   [815 160 920 190];
        'Internal Flow Factor Display',[815 205 920 235];
        'Internal Efficiency Display',[815 250 920 280];
        'Effective Rth Display',      [815 295 920 325];
        'External RhoCp Display',     [815 385 920 415];
        'External Density Display',   [815 430 920 460];
        'External Flow Factor Display',[815 475 920 505];
        'External Efficiency Display',[815 520 920 550]
    };
    for idx = 1:size(display_specs,1)
        add_block('simulink/Sinks/Display', ...
            [path '/' display_specs{idx,1}], ...
            'Position', display_specs{idx,2});
    end

    % Internal signal routing.
    add_line(path, 'Internal Air Volume Fraction/1', 'Internal RhoCp Inputs/1');
    add_line(path, 'InternalDensity_kg_m3/1', 'Internal RhoCp Inputs/2');
    add_line(path, 'InternalCp_J_kgK/1', 'Internal RhoCp Inputs/3');
    add_line(path, 'Internal RhoCp Inputs/1', 'Internal Effective RhoCp/1');

    add_line(path, 'Internal Air Volume Fraction/1', 'Internal Density Inputs/1');
    add_line(path, 'InternalDensity_kg_m3/1', 'Internal Density Inputs/2');
    add_line(path, 'Internal Density Inputs/1', 'Internal Effective Density/1');

    add_line(path, 'Internal Air Volume Fraction/1', ...
        'Internal Flow Capacity Factor/1');
    add_line(path, 'Internal Air Volume Fraction/1', ...
        'Internal Efficiency Factor/1');
    add_line(path, 'Internal Air Volume Fraction/1', 'Rth Inputs/1');
    add_line(path, 'InternalConductivity_W_mK/1', 'Rth Inputs/2');
    add_line(path, 'Rth Inputs/1', 'Effective Coldplate Rth/1');

    % External signal routing.
    add_line(path, 'External Air Volume Fraction/1', 'External RhoCp Inputs/1');
    add_line(path, 'ExternalDensity_kg_m3/1', 'External RhoCp Inputs/2');
    add_line(path, 'ExternalCp_J_kgK/1', 'External RhoCp Inputs/3');
    add_line(path, 'External RhoCp Inputs/1', 'External Effective RhoCp/1');

    add_line(path, 'External Air Volume Fraction/1', 'External Density Inputs/1');
    add_line(path, 'ExternalDensity_kg_m3/1', 'External Density Inputs/2');
    add_line(path, 'External Density Inputs/1', 'External Effective Density/1');
    add_line(path, 'External Air Volume Fraction/1', ...
        'External Flow Capacity Factor/1');
    add_line(path, 'External Air Volume Fraction/1', ...
        'External Efficiency Factor/1');

    % Outputs and displays.
    connect_output(path, 'Internal Air Volume Fraction', ...
        'InternalAirFraction', 'Internal Air Display');
    connect_output(path, 'External Air Volume Fraction', ...
        'ExternalAirFraction', 'External Air Display');
    connect_output(path, 'Internal Effective RhoCp', ...
        'InternalRhoCp_J_m3K', 'Internal RhoCp Display');
    connect_output(path, 'Internal Effective Density', ...
        'InternalDensity_kg_m3', 'Internal Density Display');
    connect_output(path, 'Internal Flow Capacity Factor', ...
        'InternalFlowCapacityFactor', 'Internal Flow Factor Display');
    connect_output(path, 'Internal Efficiency Factor', ...
        'InternalEfficiencyFactor', 'Internal Efficiency Display');
    connect_output(path, 'Effective Coldplate Rth', ...
        'EffectiveRth_K_W', 'Effective Rth Display');
    connect_output(path, 'External Effective RhoCp', ...
        'ExternalRhoCp_J_m3K', 'External RhoCp Display');
    connect_output(path, 'External Effective Density', ...
        'ExternalDensity_kg_m3', 'External Density Display');
    connect_output(path, 'External Flow Capacity Factor', ...
        'ExternalFlowCapacityFactor', 'External Flow Factor Display');
    connect_output(path, 'External Efficiency Factor', ...
        'ExternalEfficiencyFactor', 'External Efficiency Display');

    add_dashboard_slider(path, 'Tune Internal Aeration', ...
        'Internal Air Volume Fraction', 'Value', [0 0.01 0.10], ...
        [555 55 740 105]);
    add_dashboard_slider(path, 'Tune External Aeration', ...
        'External Air Volume Fraction', 'Value', [0 0.01 0.10], ...
        [555 420 740 470]);

    Simulink.Annotation(path, sprintf([ ...
        'AERATION MODEL\n' ...
        'alpha is free-gas volume fraction, not dissolved gas.\n' ...
        'It changes volumetric heat capacity, density, pump capacity, ' ...
        'pump efficiency, and cold-plate thermal resistance.']));
end

function connect_output(path, source_block, output_block, display_block)
    add_line(path, [source_block '/1'], [output_block '/1']);
    add_line(path, [source_block '/1'], [display_block '/1']);
end
