function build_scenario_subsystem(path)
    add_block('simulink/Sources/Step', [path '/IT Load Profile'], ...
        'Time', 'load_step_time_s', ...
        'Before', 'initial_load_fraction', ...
        'After', 'final_load_fraction', ...
        'Position', [35 45 105 80]);
    add_block('simulink/Sources/Constant', [path '/Ambient Wet Bulb C'], ...
        'Value', 'ambient_wet_bulb_C', ...
        'Position', [35 115 105 145]);
    add_block('simulink/Sources/Constant', [path '/Electricity Price per kWh'], ...
        'Value', 'electricity_price_per_kWh', ...
        'Position', [35 180 120 210]);
    add_block('simulink/Sources/Constant', [path '/Operating Months'], ...
        'Value', 'operating_months', ...
        'Position', [35 245 120 275]);

    add_out(path, 'LoadFraction', 1, [200 50 230 70]);
    add_out(path, 'AmbientWetBulbC', 2, [200 120 230 140]);
    add_out(path, 'ElectricityPrice', 3, [200 185 230 205]);
    add_out(path, 'OperatingMonths', 4, [200 250 230 270]);

    add_line(path, 'IT Load Profile/1', 'LoadFraction/1');
    add_line(path, 'Ambient Wet Bulb C/1', 'AmbientWetBulbC/1');
    add_line(path, 'Electricity Price per kWh/1', 'ElectricityPrice/1');
    add_line(path, 'Operating Months/1', 'OperatingMonths/1');
end
