function build_aeration_subsystem(path)
%BUILD_AERATION_SUBSYSTEM Calculate free-gas mixture and pump effects.
%
% Inputs are clean-liquid properties from the Fluid Properties subsystem.
% The two air-volume-fraction Constant blocks are tunable during simulation
% using Dashboard Sliders. The outputs are explicit signals consumed by the
% internal and external hydraulic black boxes.
%
% The model separates:
%   1. useful liquid flow, determined from clean-liquid rho*Cp;
%   2. pump mixture flow, increased by 1/(1-alpha);
%   3. mixture density for homogeneous pressure-loss calculations; and
%   4. pump hydraulic-efficiency degradation.

    alpha_i = evalin('base', 'air_void_fraction_internal');
    alpha_e = evalin('base', 'air_void_fraction_external');

    add_in(path, 'InternalCp_J_kgK', 1, [25 50 55 70]);
    add_in(path, 'CleanInternalDensity_kg_m3', 2, [25 105 55 125]);
    add_in(path, 'InternalConductivity_W_mK', 3, [25 160 55 180]);
    add_in(path, 'ExternalCp_J_kgK', 4, [25 330 55 350]);
    add_in(path, 'CleanExternalDensity_kg_m3', 5, [25 385 55 405]);

    add_block('simulink/Sources/Constant', ...
        [path '/Internal Air Volume Fraction'], ...
        'Value', num2str(alpha_i, 15), 'Position', [95 215 185 245]);
    add_block('simulink/Sources/Constant', ...
        [path '/External Air Volume Fraction'], ...
        'Value', num2str(alpha_e, 15), 'Position', [95 440 185 470]);

    % Internal clean-liquid volumetric heat capacity.
    add_block('simulink/Signal Routing/Mux', [path '/Internal Liquid RhoCp Inputs'], ...
        'Inputs', '2', 'Position', [235 40 255 105]);
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/Internal Liquid RhoCp'], ...
        'Expr', 'u(1)*u(2)', ...
        'Position', [305 50 500 95]);

    % Internal homogeneous mixture density.
    add_block('simulink/Signal Routing/Mux', [path '/Internal Density Inputs'], ...
        'Inputs', '2', 'Position', [235 120 255 180]);
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/Internal Mixture Density'], ...
        'Expr', '(1-u(1))*u(2)+u(1)*rho_air_kg_m3', ...
        'Position', [305 125 500 170]);

    % Constant-liquid-flow mixture multiplier and pump efficiency ratio.
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/Internal Mixture Flow Factor'], ...
        'Expr', '1/(1-u)', ...
        'Position', [305 205 500 245]);
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/Internal Pump Efficiency Ratio'], ...
        'Expr', ['(minimum_pump_efficiency_fraction+' ...
                 '(1-internal_efficiency_derating_coefficient*u)+sqrt((' ...
                 'minimum_pump_efficiency_fraction-' ...
                 '(1-internal_efficiency_derating_coefficient*u))^2))/2'], ...
        'Position', [305 260 500 300]);

    % Conductivity-sensitive clean Rth followed by aeration penalty.
    add_block('simulink/Signal Routing/Mux', [path '/Rth Inputs'], ...
        'Inputs', '2', 'Position', [235 205 255 275]);
    rth_expr = [ ...
        'Rth_chip_to_coolant_K_W*' ...
        '((1-coldplate_fluid_side_resistance_fraction)+' ...
        'coldplate_fluid_side_resistance_fraction*' ...
        'k_internal_reference_W_mK/u(2))*' ...
        '(1+Rth_aeration_sensitivity*u(1))'];
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/Effective Coldplate Rth'], ...
        'Expr', rth_expr, 'Position', [555 220 780 275]);

    % External clean-liquid rhoCp, mixture density, flow multiplier and pump
    % efficiency ratio.
    add_block('simulink/Signal Routing/Mux', [path '/External Liquid RhoCp Inputs'], ...
        'Inputs', '2', 'Position', [235 325 255 390]);
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/External Liquid RhoCp'], ...
        'Expr', 'u(1)*u(2)', ...
        'Position', [305 335 500 380]);

    add_block('simulink/Signal Routing/Mux', [path '/External Density Inputs'], ...
        'Inputs', '2', 'Position', [235 405 255 465]);
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/External Mixture Density'], ...
        'Expr', '(1-u(1))*u(2)+u(1)*rho_air_kg_m3', ...
        'Position', [305 410 500 455]);

    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/External Mixture Flow Factor'], ...
        'Expr', '1/(1-u)', ...
        'Position', [305 485 500 525]);
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/External Pump Efficiency Ratio'], ...
        'Expr', ['(minimum_pump_efficiency_fraction+' ...
                 '(1-external_efficiency_derating_coefficient*u)+sqrt((' ...
                 'minimum_pump_efficiency_fraction-' ...
                 '(1-external_efficiency_derating_coefficient*u))^2))/2'], ...
        'Position', [305 540 500 580]);

    % Interface outputs. Port numbers are preserved to keep the top-level
    % subsystem interfaces stable.
    add_out(path, 'InternalAirFraction', 1, [980 30 1010 50]);
    add_out(path, 'ExternalAirFraction', 2, [980 75 1010 95]);
    add_out(path, 'InternalLiquidRhoCp_J_m3K', 3, [980 120 1010 140]);
    add_out(path, 'InternalMixtureDensity_kg_m3', 4, [980 165 1010 185]);
    add_out(path, 'InternalMixtureFlowFactor', 5, [980 210 1010 230]);
    add_out(path, 'InternalPumpEfficiencyRatio', 6, [980 255 1010 275]);
    add_out(path, 'EffectiveRth_K_W', 7, [980 300 1010 320]);
    add_out(path, 'ExternalLiquidRhoCp_J_m3K', 8, [980 390 1010 410]);
    add_out(path, 'ExternalMixtureDensity_kg_m3', 9, [980 435 1010 455]);
    add_out(path, 'ExternalMixtureFlowFactor', 10, [980 480 1010 500]);
    add_out(path, 'ExternalPumpEfficiencyRatio', 11, [980 525 1010 545]);

    % Internal signal routing.
    add_line(path, 'CleanInternalDensity_kg_m3/1', 'Internal Liquid RhoCp Inputs/1');
    add_line(path, 'InternalCp_J_kgK/1', 'Internal Liquid RhoCp Inputs/2');
    add_line(path, 'Internal Liquid RhoCp Inputs/1', 'Internal Liquid RhoCp/1');
    add_line(path, 'Internal Air Volume Fraction/1', 'Internal Density Inputs/1');
    add_line(path, 'CleanInternalDensity_kg_m3/1', 'Internal Density Inputs/2');
    add_line(path, 'Internal Density Inputs/1', 'Internal Mixture Density/1');
    add_line(path, 'Internal Air Volume Fraction/1', 'Internal Mixture Flow Factor/1');
    add_line(path, 'Internal Air Volume Fraction/1', 'Internal Pump Efficiency Ratio/1');
    add_line(path, 'Internal Air Volume Fraction/1', 'Rth Inputs/1');
    add_line(path, 'InternalConductivity_W_mK/1', 'Rth Inputs/2');
    add_line(path, 'Rth Inputs/1', 'Effective Coldplate Rth/1');

    % External signal routing.
    add_line(path, 'CleanExternalDensity_kg_m3/1', 'External Liquid RhoCp Inputs/1');
    add_line(path, 'ExternalCp_J_kgK/1', 'External Liquid RhoCp Inputs/2');
    add_line(path, 'External Liquid RhoCp Inputs/1', 'External Liquid RhoCp/1');
    add_line(path, 'External Air Volume Fraction/1', 'External Density Inputs/1');
    add_line(path, 'CleanExternalDensity_kg_m3/1', 'External Density Inputs/2');
    add_line(path, 'External Density Inputs/1', 'External Mixture Density/1');
    add_line(path, 'External Air Volume Fraction/1', 'External Mixture Flow Factor/1');
    add_line(path, 'External Air Volume Fraction/1', 'External Pump Efficiency Ratio/1');

    connect_output(path, 'Internal Air Volume Fraction', 'InternalAirFraction', 'Internal Air Display');
    connect_output(path, 'External Air Volume Fraction', 'ExternalAirFraction', 'External Air Display');
    connect_output(path, 'Internal Liquid RhoCp', 'InternalLiquidRhoCp_J_m3K', 'Internal Liquid RhoCp Display');
    connect_output(path, 'Internal Mixture Density', 'InternalMixtureDensity_kg_m3', 'Internal Mixture Density Display');
    connect_output(path, 'Internal Mixture Flow Factor', 'InternalMixtureFlowFactor', 'Internal Mixture Flow Factor Display');
    connect_output(path, 'Internal Pump Efficiency Ratio', 'InternalPumpEfficiencyRatio', 'Internal Pump Efficiency Ratio Display');
    connect_output(path, 'Effective Coldplate Rth', 'EffectiveRth_K_W', 'Effective Rth Display');
    connect_output(path, 'External Liquid RhoCp', 'ExternalLiquidRhoCp_J_m3K', 'External Liquid RhoCp Display');
    connect_output(path, 'External Mixture Density', 'ExternalMixtureDensity_kg_m3', 'External Mixture Density Display');
    connect_output(path, 'External Mixture Flow Factor', 'ExternalMixtureFlowFactor', 'External Mixture Flow Factor Display');
    connect_output(path, 'External Pump Efficiency Ratio', 'ExternalPumpEfficiencyRatio', 'External Pump Efficiency Ratio Display');

    add_dashboard_slider(path, 'Tune Internal Aeration', ...
        'Internal Air Volume Fraction', 'Value', [0 0.01 0.10], [555 55 740 105]);
    add_dashboard_slider(path, 'Tune External Aeration', ...
        'External Air Volume Fraction', 'Value', [0 0.01 0.10], [555 420 740 470]);

    Simulink.Annotation(path, sprintf([ ...
        'AERATION MODEL\n' ...
        'alpha is free-gas volume fraction, not dissolved gas.\n' ...
        'Useful liquid flow is kept separate from pump mixture flow.\n' ...
        'The model outputs mixture density, 1/(1-alpha), pump efficiency ratio, and cold-plate Rth correction.']));
end

function connect_output(path, source_block, output_block, display_block)
    add_block('simulink/Sinks/Display', [path '/' display_block], ...
        'Position', [800 25+45*str2double(get_param([path '/' output_block], 'Port')) ...
        940 55+45*str2double(get_param([path '/' output_block], 'Port'))]);
    add_line(path, [source_block '/1'], [output_block '/1']);
    add_line(path, [source_block '/1'], [display_block '/1']);
end
