function build_tower_subsystem(path)
% Reduced-order closed-circuit cooling-tower black box.
    add_in(path, 'HeatLoad_kW', 1, [25 45 55 65]);
    add_in(path, 'Flow_m3h', 2, [25 115 55 135]);
    add_in(path, 'LoopDeltaT_K', 3, [25 185 55 205]);
    add_in(path, 'AmbientWetBulb_C', 4, [25 255 55 275]);

    add_block('simulink/Signal Routing/Mux', [path '/Tower Inputs'], ...
        'Inputs', '4', 'Position', [110 60 130 245]);

    supply_expr = [ ...
        'u(4)+tower_design_approach_K+' ...
        'tower_approach_load_sensitivity_K*' ...
        'min(max(u(1)/tower_design_heat_kW,0),1.2)^2+' ...
        'tower_approach_low_flow_sensitivity_K*' ...
        'max(0,1-min(max(u(2)/tower_design_flow_m3h,' ...
        'tower_minimum_flow_ratio),2))'];
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/Supply Temperature Correlation'], ...
        'Expr', supply_expr, 'Position', [200 45 445 105]);

    fan_expr = [ ...
        'tower_fan_design_kW*' ...
        'min(max((u(1)/tower_design_heat_kW)*' ...
        '(u(3)/tower_design_range_K)*' ...
        '(1+tower_ambient_power_sensitivity_per_K*' ...
        'max(u(4)-tower_design_wet_bulb_C,0)),0),1)^3'];
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/Fan Power Correlation'], ...
        'Expr', fan_expr, 'Position', [200 130 445 190]);

    spray_expr = [ ...
        'tower_spray_pump_design_kW*' ...
        'min(max(u/tower_design_heat_kW,0),1.2)'];
    add_block('simulink/User-Defined Functions/Fcn', ...
        [path '/Spray Pump Correlation'], ...
        'Expr', spray_expr, 'Position', [200 220 420 270]);

    add_block('simulink/Math Operations/Sum', [path '/Tower Power kW'], ...
        'Inputs', '++', 'Position', [510 155 560 220]);
    add_block('simulink/Sources/Constant', [path '/Design Heat kW'], ...
        'Value', 'tower_design_heat_kW', ...
        'Position', [500 275 590 305]);
    add_block('simulink/Math Operations/Sum', [path '/Capacity Margin kW'], ...
        'Inputs', '+-', 'Position', [650 255 700 320]);

    add_out(path, 'SupplyTemperature_C', 1, [790 70 820 90]);
    add_out(path, 'TowerPower_kW', 2, [790 175 820 195]);
    add_out(path, 'FanPower_kW', 3, [790 130 820 150]);
    add_out(path, 'SprayPumpPower_kW', 4, [790 230 820 250]);
    add_out(path, 'CapacityMargin_kW', 5, [790 290 820 310]);

    add_line(path, 'HeatLoad_kW/1', 'Tower Inputs/1');
    add_line(path, 'Flow_m3h/1', 'Tower Inputs/2');
    add_line(path, 'LoopDeltaT_K/1', 'Tower Inputs/3');
    add_line(path, 'AmbientWetBulb_C/1', 'Tower Inputs/4');
    add_line(path, 'Tower Inputs/1', 'Supply Temperature Correlation/1');
    add_line(path, 'Tower Inputs/1', 'Fan Power Correlation/1');
    add_line(path, 'HeatLoad_kW/1', 'Spray Pump Correlation/1');

    add_line(path, 'Supply Temperature Correlation/1', ...
        'SupplyTemperature_C/1');
    add_line(path, 'Fan Power Correlation/1', 'FanPower_kW/1');
    add_line(path, 'Spray Pump Correlation/1', 'SprayPumpPower_kW/1');
    add_line(path, 'Fan Power Correlation/1', 'Tower Power kW/1');
    add_line(path, 'Spray Pump Correlation/1', 'Tower Power kW/2');
    add_line(path, 'Tower Power kW/1', 'TowerPower_kW/1');

    add_line(path, 'Design Heat kW/1', 'Capacity Margin kW/1');
    add_line(path, 'HeatLoad_kW/1', 'Capacity Margin kW/2');
    add_line(path, 'Capacity Margin kW/1', 'CapacityMargin_kW/1');
end
