function build_scenario_subsystem(path)
%BUILD_SCENARIO_SUBSYSTEM Operating boundary conditions and live controls.

    ambient_value = evalin('base', 'ambient_wet_bulb_C');
    price_value = evalin('base', 'electricity_price_per_kWh');
    months_value = evalin('base', 'operating_months');

    add_block('simulink/Sources/Step', [path '/IT Load Profile'], ...
        'Time', 'load_step_time_s', ...
        'Before', 'initial_load_fraction', ...
        'After', 'final_load_fraction', ...
        'Position', [35 45 105 80]);
    add_block('simulink/Math Operations/Gain', ...
        [path '/Interactive Load Multiplier'], ...
        'Gain', '1.0', 'Position', [155 40 260 85]);

    add_block('simulink/Sources/Constant', [path '/Ambient Wet Bulb C'], ...
        'Value', num2str(ambient_value, 15), ...
        'Position', [35 145 105 175]);
    add_block('simulink/Sources/Constant', [path '/Electricity Price per kWh'], ...
        'Value', num2str(price_value, 15), ...
        'Position', [35 245 120 275]);
    add_block('simulink/Sources/Constant', [path '/Operating Months'], ...
        'Value', num2str(months_value, 15), ...
        'Position', [35 330 120 360]);

    add_out(path, 'LoadFraction', 1, [520 55 550 75]);
    add_out(path, 'AmbientWetBulbC', 2, [520 155 550 175]);
    add_out(path, 'ElectricityPrice', 3, [520 255 550 275]);
    add_out(path, 'OperatingMonths', 4, [520 340 550 360]);

    add_block('simulink/Sinks/Display', [path '/Load Fraction Display'], ...
        'Position', [385 45 470 80]);
    add_block('simulink/Sinks/Display', [path '/Wet Bulb Display'], ...
        'Position', [385 145 470 180]);
    add_block('simulink/Sinks/Display', [path '/Electricity Price Display'], ...
        'Position', [385 245 470 280]);
    add_block('simulink/Sinks/Display', [path '/Operating Months Display'], ...
        'Position', [385 330 470 365]);

    add_line(path, 'IT Load Profile/1', 'Interactive Load Multiplier/1');
    add_line(path, 'Interactive Load Multiplier/1', 'LoadFraction/1');
    add_line(path, 'Interactive Load Multiplier/1', 'Load Fraction Display/1');
    add_line(path, 'Ambient Wet Bulb C/1', 'AmbientWetBulbC/1');
    add_line(path, 'Ambient Wet Bulb C/1', 'Wet Bulb Display/1');
    add_line(path, 'Electricity Price per kWh/1', 'ElectricityPrice/1');
    add_line(path, 'Electricity Price per kWh/1', ...
        'Electricity Price Display/1');
    add_line(path, 'Operating Months/1', 'OperatingMonths/1');
    add_line(path, 'Operating Months/1', 'Operating Months Display/1');

    add_dashboard_slider(path, 'Tune IT Load Fraction', ...
        'Interactive Load Multiplier', 'Gain', [0 0.1 1.2], ...
        [155 90 330 140]);
    add_dashboard_slider(path, 'Tune Ambient Wet Bulb', ...
        'Ambient Wet Bulb C', 'Value', [-10 5 40], ...
        [155 155 330 205]);

    Simulink.Annotation(path, sprintf([ ...
        'OPERATING SCENARIO\n' ...
        'IT load and wet-bulb temperature can be tuned during simulation.\n' ...
        'Electricity price and months feed the flat-price projection; ' ...
        'TCO uses the configured annual escalation schedule with no discounting.']));
end
