function build_tco_subsystem(path)
% Nominal TCO black box for the configured analysis horizon.
%
% Two TCO boundaries are reported:
% 1. Facility TCO includes all facility electricity, including IT power.
% 2. Cooling TCO includes only cooling electricity plus cooling CAPEX,
%    fluid, maintenance, replacement, and disposal costs.

    add_in(path, 'AnnualFacilityEnergy_kWh', 1, [25 70 55 90]);
    add_in(path, 'AnnualCoolingEnergy_kWh', 2, [25 150 55 170]);

    add_block('simulink/Math Operations/Gain', ...
        [path '/Nominal Facility Electricity'], ...
        'Gain', 'electricity_nominal_price_factor_horizon', ...
        'Position', [120 225 285 275]);
    add_block('simulink/Math Operations/Gain', ...
        [path '/Nominal Cooling Electricity'], ...
        'Gain', 'electricity_nominal_price_factor_horizon', ...
        'Position', [120 305 285 355]);

    add_block('simulink/Sources/Constant', [path '/Initial Cooling CAPEX'], ...
        'Value', 'initial_cooling_CAPEX', ...
        'Position', [355 405 475 435]);
    add_block('simulink/Sources/Constant', ...
        [path '/Nominal Nonenergy OPEX'], ...
        'Value', 'nonenergy_nominal_total_horizon', ...
        'Position', [355 505 500 535]);

    add_block('simulink/Math Operations/Sum', ...
        [path '/Nominal Facility TCO'], 'Inputs', '+++', ...
        'Position', [575 295 630 385]);
    add_block('simulink/Math Operations/Sum', ...
        [path '/Nominal Cooling TCO'], 'Inputs', '+++', ...
        'Position', [575 415 630 505]);

    add_out(path, 'InitialCoolingCAPEX', 1, [755 40 785 60]);
    add_out(path, 'NominalFacilityTCO', 2, [755 220 785 240]);
    add_out(path, 'NominalCoolingTCO', 3, [755 280 785 300]);
    add_line(path, 'AnnualFacilityEnergy_kWh/1', ...
        'Nominal Facility Electricity/1');
    add_line(path, 'AnnualCoolingEnergy_kWh/1', ...
        'Nominal Cooling Electricity/1');

    add_line(path, 'Nominal Facility Electricity/1', ...
        'Nominal Facility TCO/1');
    add_line(path, 'Initial Cooling CAPEX/1', ...
        'Nominal Facility TCO/2');
    add_line(path, 'Nominal Nonenergy OPEX/1', ...
        'Nominal Facility TCO/3');

    add_line(path, 'Nominal Cooling Electricity/1', ...
        'Nominal Cooling TCO/1');
    add_line(path, 'Initial Cooling CAPEX/1', ...
        'Nominal Cooling TCO/2');
    add_line(path, 'Nominal Nonenergy OPEX/1', ...
        'Nominal Cooling TCO/3');

    add_line(path, 'Initial Cooling CAPEX/1', 'InitialCoolingCAPEX/1');
    add_line(path, 'Nominal Facility TCO/1', 'NominalFacilityTCO/1');
    add_line(path, 'Nominal Cooling TCO/1', 'NominalCoolingTCO/1');
end
