%% build_datacenter_D2C_v1.m
% Reduced-order direct-to-chip data-center rack model.
%
% Architecture:
%   48U IT rack -> internal cold-plate loop -> rack CDU/HX
%   -> external PG25 loop -> closed-circuit heat-rejection unit
%   -> facility electrical power and energy accounting
%
% The script generates a NEW model. It does not overwrite the previous v0
% model. Edit the parameters in Section 1, then run this script again.
%
% Unit convention:
%   Power in the signal diagram: kW
%   Heat flow in hydraulic/thermal equations: W
%   Pressure: Pa
%   Flow: m^3/s internally, with m^3/h outputs
%   Temperature: degC
%
% Broad-scope assumptions:
%   - Steady-state flow required from Q = m_dot*cp*DeltaT
%   - Pressure losses scale approximately with flow^2
%   - Cold-plate thermal resistance is the TOTAL chip-to-bulk-coolant
%     resistance for one cooling path
%   - External supply temperature is imposed
%   - Heat-rejection power is a reduced-order load-based model
%
% Later versions can replace each reduced-order section with Simscape
% Fluids components without changing the top-level energy architecture.

clearvars;
clc;

%% 1. USER PARAMETERS

model = 'DataCenter_D2C_Rack_v1';

% Simulation
simulation_time_s = 3600;
load_step_time_s  = 1800;
initial_load_fraction = 0.50;
final_load_fraction   = 1.00;

% Rack
rack_U = 48;
kW_per_U = 1.0;
heat_capture_fraction = 1.00;
coldplate_paths = 48;              % One equivalent path per U
Rth_chip_to_coolant_K_W = 0.020;   % USER INPUT: K/W per cooling path

% External PG25 fluid, constant properties requested by user
nu_external_cSt = 1.95;
rho_external_kg_m3 = 1000;
cp_external_J_kgK = 3980;          % 3.98 J/g/K
k_external_W_mK = 0.49;
mu_external_Pas = nu_external_cSt * 1e-6 * rho_external_kg_m3;

% Internal cold-plate fluid.
% Placeholder: same properties as external PG25 until another fluid is set.
nu_internal_cSt = nu_external_cSt;
rho_internal_kg_m3 = rho_external_kg_m3;
cp_internal_J_kgK = cp_external_J_kgK;
k_internal_W_mK = k_external_W_mK;
mu_internal_Pas = nu_internal_cSt * 1e-6 * rho_internal_kg_m3;

% Thermal targets
deltaT_internal_K = 6;
deltaT_external_K = 5;
T_external_supply_C = 25;
HX_approach_K = 3;                  % Internal supply minus external supply

% Internal loop hydraulic model
dp_internal_ref_Pa = 120e3;
eta_internal_pump = 0.65;

% External PG25 loop hydraulic model
dp_external_ref_Pa = 80e3;
eta_external_pump = 0.70;

% Reference fluid values used in pressure-loss scaling
mu_internal_ref_Pas = mu_internal_Pas;
rho_internal_ref_kg_m3 = rho_internal_kg_m3;
mu_external_ref_Pas = mu_external_Pas;
rho_external_ref_kg_m3 = rho_external_kg_m3;
mu_pressure_exponent = 0.20;

% Closed-circuit cooling tower / heat-rejection unit
tower_design_heat_kW = 60;
tower_fan_design_kW = 1.50;
tower_spray_pump_design_kW = 0.50;

% Other rack/facility auxiliary power
auxiliary_power_kW = 0.50;

% Derived design values
rack_design_power_kW = rack_U * kW_per_U;
Q_design_W = rack_design_power_kW * heat_capture_fraction * 1000;

mdot_internal_ref_kg_s = Q_design_W / ...
    (cp_internal_J_kgK * deltaT_internal_K);
Vdot_internal_ref_m3s = mdot_internal_ref_kg_s / rho_internal_kg_m3;

% Include internal pump design estimate in CDU reference heat
P_internal_pump_design_kW = ...
    dp_internal_ref_Pa * Vdot_internal_ref_m3s / ...
    (eta_internal_pump * 1000);

Q_external_design_W = ...
    (rack_design_power_kW * heat_capture_fraction + ...
    P_internal_pump_design_kW) * 1000;

mdot_external_ref_kg_s = Q_external_design_W / ...
    (cp_external_J_kgK * deltaT_external_K);
Vdot_external_ref_m3s = mdot_external_ref_kg_s / rho_external_kg_m3;

fprintf('PG25 dynamic viscosity used: %.6f Pa.s\n', mu_external_Pas);
fprintf('Rack design IT load: %.1f kW\n', rack_design_power_kW);
fprintf('Reference internal flow: %.2f m^3/h\n', ...
    Vdot_internal_ref_m3s * 3600);
fprintf('Reference external flow: %.2f m^3/h\n', ...
    Vdot_external_ref_m3s * 3600);

%% 2. CREATE A NEW VERSIONED MODEL

if bdIsLoaded(model)
    close_system(model, 0);
end

if isfile([model '.slx'])
    delete([model '.slx']);
end

new_system(model);
open_system(model);

set_param(model, ...
    'StopTime', num2str(simulation_time_s), ...
    'Solver', 'ode45');

%% 3. IT LOAD AND HEAT CAPTURE

add_block('simulink/Sources/Step', [model '/IT Load Fraction'], ...
    'Time', num2str(load_step_time_s), ...
    'Before', num2str(initial_load_fraction), ...
    'After', num2str(final_load_fraction), ...
    'Position', [40 70 105 105]);

add_block('simulink/Math Operations/Gain', [model '/Rack IT Power kW'], ...
    'Gain', 'rack_design_power_kW', ...
    'Position', [155 65 255 110]);

add_block('simulink/Math Operations/Gain', [model '/Heat to Liquid kW'], ...
    'Gain', 'heat_capture_fraction', ...
    'Position', [305 65 405 110]);

add_line(model, 'IT Load Fraction/1', 'Rack IT Power kW/1', ...
    'autorouting', 'on');
add_line(model, 'Rack IT Power kW/1', 'Heat to Liquid kW/1', ...
    'autorouting', 'on');

%% 4. CDU TEMPERATURE BOUNDARY

add_block('simulink/Sources/Constant', ...
    [model '/External Supply Temperature C'], ...
    'Value', 'T_external_supply_C', ...
    'Position', [40 225 135 255]);

add_block('simulink/Sources/Constant', [model '/HX Approach K'], ...
    'Value', 'HX_approach_K', ...
    'Position', [40 280 135 310]);

add_block('simulink/Math Operations/Sum', ...
    [model '/Internal Supply Temperature C'], ...
    'Inputs', '++', ...
    'Position', [185 240 225 295]);

add_line(model, 'External Supply Temperature C/1', ...
    'Internal Supply Temperature C/1', 'autorouting', 'on');
add_line(model, 'HX Approach K/1', ...
    'Internal Supply Temperature C/2', 'autorouting', 'on');

%% 5. INTERNAL COLD-PLATE LOOP

add_block('simulink/Math Operations/Gain', [model '/Internal Heat W'], ...
    'Gain', '1000', ...
    'Position', [455 65 525 110]);

add_block('simulink/Sources/Constant', [model '/Internal cp'], ...
    'Value', 'cp_internal_J_kgK', ...
    'Position', [455 145 525 175]);

add_block('simulink/Sources/Constant', [model '/Internal Target DeltaT'], ...
    'Value', 'deltaT_internal_K', ...
    'Position', [455 200 525 230]);

add_block('simulink/Math Operations/Product', ...
    [model '/Internal cp x DeltaT'], ...
    'Inputs', '**', ...
    'Position', [575 155 630 220]);

add_block('simulink/Math Operations/Product', ...
    [model '/Internal Mass Flow kg_s'], ...
    'Inputs', '*/', ...
    'Position', [680 75 735 135]);

add_block('simulink/Sources/Constant', [model '/Internal Density'], ...
    'Value', 'rho_internal_kg_m3', ...
    'Position', [680 165 750 195]);

add_block('simulink/Math Operations/Product', ...
    [model '/Internal Volume Flow m3_s'], ...
    'Inputs', '*/', ...
    'Position', [790 90 845 150]);

add_block('simulink/Math Operations/Gain', ...
    [model '/Internal Flow m3_h'], ...
    'Gain', '3600', ...
    'Position', [895 85 980 130]);

add_line(model, 'Heat to Liquid kW/1', 'Internal Heat W/1', ...
    'autorouting', 'on');
add_line(model, 'Internal cp/1', 'Internal cp x DeltaT/1', ...
    'autorouting', 'on');
add_line(model, 'Internal Target DeltaT/1', ...
    'Internal cp x DeltaT/2', 'autorouting', 'on');
add_line(model, 'Internal Heat W/1', 'Internal Mass Flow kg_s/1', ...
    'autorouting', 'on');
add_line(model, 'Internal cp x DeltaT/1', ...
    'Internal Mass Flow kg_s/2', 'autorouting', 'on');
add_line(model, 'Internal Mass Flow kg_s/1', ...
    'Internal Volume Flow m3_s/1', 'autorouting', 'on');
add_line(model, 'Internal Density/1', ...
    'Internal Volume Flow m3_s/2', 'autorouting', 'on');
add_line(model, 'Internal Volume Flow m3_s/1', ...
    'Internal Flow m3_h/1', 'autorouting', 'on');

% Internal pressure drop and pump power
add_block('simulink/Math Operations/Gain', ...
    [model '/Internal Flow Ratio'], ...
    'Gain', '1/Vdot_internal_ref_m3s', ...
    'Position', [895 160 980 205]);

add_block('simulink/Math Operations/Math Function', ...
    [model '/Internal Flow Ratio Squared'], ...
    'Operator', 'square', ...
    'Position', [1030 160 1100 205]);

internal_dp_gain = [ ...
    'dp_internal_ref_Pa*' ...
    '(mu_internal_Pas/mu_internal_ref_Pas)^mu_pressure_exponent*' ...
    '(rho_internal_kg_m3/rho_internal_ref_kg_m3)' ];

add_block('simulink/Math Operations/Gain', ...
    [model '/Internal Pressure Drop Pa'], ...
    'Gain', internal_dp_gain, ...
    'Position', [1150 155 1270 210]);

add_block('simulink/Math Operations/Product', ...
    [model '/Internal Hydraulic Power W'], ...
    'Inputs', '**', ...
    'Position', [1320 95 1380 155]);

add_block('simulink/Math Operations/Gain', ...
    [model '/Internal Pump Power kW'], ...
    'Gain', '1/(eta_internal_pump*1000)', ...
    'Position', [1430 95 1540 150]);

add_line(model, 'Internal Volume Flow m3_s/1', ...
    'Internal Flow Ratio/1', 'autorouting', 'on');
add_line(model, 'Internal Flow Ratio/1', ...
    'Internal Flow Ratio Squared/1', 'autorouting', 'on');
add_line(model, 'Internal Flow Ratio Squared/1', ...
    'Internal Pressure Drop Pa/1', 'autorouting', 'on');
add_line(model, 'Internal Pressure Drop Pa/1', ...
    'Internal Hydraulic Power W/1', 'autorouting', 'on');
add_line(model, 'Internal Volume Flow m3_s/1', ...
    'Internal Hydraulic Power W/2', 'autorouting', 'on');
add_line(model, 'Internal Hydraulic Power W/1', ...
    'Internal Pump Power kW/1', 'autorouting', 'on');

%% 6. INTERNAL TEMPERATURES AND CHIP TEMPERATURE

add_block('simulink/Math Operations/Product', ...
    [model '/Internal mDot x cp'], ...
    'Inputs', '**', ...
    'Position', [790 270 850 330]);

add_block('simulink/Math Operations/Product', ...
    [model '/Internal Actual DeltaT K'], ...
    'Inputs', '*/', ...
    'Position', [900 265 960 325]);

add_block('simulink/Math Operations/Sum', ...
    [model '/Internal Return Temperature C'], ...
    'Inputs', '++', ...
    'Position', [1010 250 1060 320]);

add_block('simulink/Math Operations/Sum', ...
    [model '/Internal Supply Plus Return'], ...
    'Inputs', '++', ...
    'Position', [1110 250 1160 320]);

add_block('simulink/Math Operations/Gain', ...
    [model '/Internal Mean Temperature C'], ...
    'Gain', '0.5', ...
    'Position', [1210 260 1300 310]);

add_block('simulink/Math Operations/Gain', ...
    [model '/Heat per Coldplate W'], ...
    'Gain', '1/coldplate_paths', ...
    'Position', [790 370 900 415]);

add_block('simulink/Math Operations/Gain', ...
    [model '/Chip to Coolant Temperature Rise K'], ...
    'Gain', 'Rth_chip_to_coolant_K_W', ...
    'Position', [960 365 1090 420]);

add_block('simulink/Math Operations/Sum', ...
    [model '/Estimated Chip Temperature C'], ...
    'Inputs', '++', ...
    'Position', [1360 280 1410 350]);

add_line(model, 'Internal Mass Flow kg_s/1', ...
    'Internal mDot x cp/1', 'autorouting', 'on');
add_line(model, 'Internal cp/1', ...
    'Internal mDot x cp/2', 'autorouting', 'on');
add_line(model, 'Internal Heat W/1', ...
    'Internal Actual DeltaT K/1', 'autorouting', 'on');
add_line(model, 'Internal mDot x cp/1', ...
    'Internal Actual DeltaT K/2', 'autorouting', 'on');
add_line(model, 'Internal Supply Temperature C/1', ...
    'Internal Return Temperature C/1', 'autorouting', 'on');
add_line(model, 'Internal Actual DeltaT K/1', ...
    'Internal Return Temperature C/2', 'autorouting', 'on');
add_line(model, 'Internal Supply Temperature C/1', ...
    'Internal Supply Plus Return/1', 'autorouting', 'on');
add_line(model, 'Internal Return Temperature C/1', ...
    'Internal Supply Plus Return/2', 'autorouting', 'on');
add_line(model, 'Internal Supply Plus Return/1', ...
    'Internal Mean Temperature C/1', 'autorouting', 'on');
add_line(model, 'Internal Heat W/1', ...
    'Heat per Coldplate W/1', 'autorouting', 'on');
add_line(model, 'Heat per Coldplate W/1', ...
    'Chip to Coolant Temperature Rise K/1', 'autorouting', 'on');
add_line(model, 'Internal Mean Temperature C/1', ...
    'Estimated Chip Temperature C/1', 'autorouting', 'on');
add_line(model, 'Chip to Coolant Temperature Rise K/1', ...
    'Estimated Chip Temperature C/2', 'autorouting', 'on');

%% 7. RACK CDU AND EXTERNAL PG25 LOOP

% Internal pump losses are assumed to enter the coolant and reach the CDU.
add_block('simulink/Math Operations/Sum', ...
    [model '/CDU Heat to External Loop kW'], ...
    'Inputs', '++', ...
    'Position', [455 470 515 535]);

add_block('simulink/Math Operations/Gain', ...
    [model '/External Heat W'], ...
    'Gain', '1000', ...
    'Position', [565 480 635 525]);

add_block('simulink/Sources/Constant', [model '/External cp'], ...
    'Value', 'cp_external_J_kgK', ...
    'Position', [565 565 635 595]);

add_block('simulink/Sources/Constant', [model '/External Target DeltaT'], ...
    'Value', 'deltaT_external_K', ...
    'Position', [565 620 635 650]);

add_block('simulink/Math Operations/Product', ...
    [model '/External cp x DeltaT'], ...
    'Inputs', '**', ...
    'Position', [685 575 740 640]);

add_block('simulink/Math Operations/Product', ...
    [model '/External Mass Flow kg_s'], ...
    'Inputs', '*/', ...
    'Position', [790 485 845 545]);

add_block('simulink/Sources/Constant', [model '/External Density'], ...
    'Value', 'rho_external_kg_m3', ...
    'Position', [790 575 860 605]);

add_block('simulink/Math Operations/Product', ...
    [model '/External Volume Flow m3_s'], ...
    'Inputs', '*/', ...
    'Position', [900 495 955 555]);

add_block('simulink/Math Operations/Gain', ...
    [model '/External Flow m3_h'], ...
    'Gain', '3600', ...
    'Position', [1005 490 1090 535]);

add_line(model, 'Heat to Liquid kW/1', ...
    'CDU Heat to External Loop kW/1', 'autorouting', 'on');
add_line(model, 'Internal Pump Power kW/1', ...
    'CDU Heat to External Loop kW/2', 'autorouting', 'on');
add_line(model, 'CDU Heat to External Loop kW/1', ...
    'External Heat W/1', 'autorouting', 'on');
add_line(model, 'External cp/1', 'External cp x DeltaT/1', ...
    'autorouting', 'on');
add_line(model, 'External Target DeltaT/1', ...
    'External cp x DeltaT/2', 'autorouting', 'on');
add_line(model, 'External Heat W/1', ...
    'External Mass Flow kg_s/1', 'autorouting', 'on');
add_line(model, 'External cp x DeltaT/1', ...
    'External Mass Flow kg_s/2', 'autorouting', 'on');
add_line(model, 'External Mass Flow kg_s/1', ...
    'External Volume Flow m3_s/1', 'autorouting', 'on');
add_line(model, 'External Density/1', ...
    'External Volume Flow m3_s/2', 'autorouting', 'on');
add_line(model, 'External Volume Flow m3_s/1', ...
    'External Flow m3_h/1', 'autorouting', 'on');

% External pressure drop and pump power
add_block('simulink/Math Operations/Gain', ...
    [model '/External Flow Ratio'], ...
    'Gain', '1/Vdot_external_ref_m3s', ...
    'Position', [1005 570 1090 615]);

add_block('simulink/Math Operations/Math Function', ...
    [model '/External Flow Ratio Squared'], ...
    'Operator', 'square', ...
    'Position', [1140 570 1210 615]);

external_dp_gain = [ ...
    'dp_external_ref_Pa*' ...
    '(mu_external_Pas/mu_external_ref_Pas)^mu_pressure_exponent*' ...
    '(rho_external_kg_m3/rho_external_ref_kg_m3)' ];

add_block('simulink/Math Operations/Gain', ...
    [model '/External Pressure Drop Pa'], ...
    'Gain', external_dp_gain, ...
    'Position', [1260 565 1380 620]);

add_block('simulink/Math Operations/Product', ...
    [model '/External Hydraulic Power W'], ...
    'Inputs', '**', ...
    'Position', [1430 495 1490 555]);

add_block('simulink/Math Operations/Gain', ...
    [model '/External Pump Power kW'], ...
    'Gain', '1/(eta_external_pump*1000)', ...
    'Position', [1540 495 1650 550]);

add_line(model, 'External Volume Flow m3_s/1', ...
    'External Flow Ratio/1', 'autorouting', 'on');
add_line(model, 'External Flow Ratio/1', ...
    'External Flow Ratio Squared/1', 'autorouting', 'on');
add_line(model, 'External Flow Ratio Squared/1', ...
    'External Pressure Drop Pa/1', 'autorouting', 'on');
add_line(model, 'External Pressure Drop Pa/1', ...
    'External Hydraulic Power W/1', 'autorouting', 'on');
add_line(model, 'External Volume Flow m3_s/1', ...
    'External Hydraulic Power W/2', 'autorouting', 'on');
add_line(model, 'External Hydraulic Power W/1', ...
    'External Pump Power kW/1', 'autorouting', 'on');

% External return temperature
add_block('simulink/Math Operations/Product', ...
    [model '/External mDot x cp'], ...
    'Inputs', '**', ...
    'Position', [900 680 960 740]);

add_block('simulink/Math Operations/Product', ...
    [model '/External Actual DeltaT K'], ...
    'Inputs', '*/', ...
    'Position', [1010 675 1070 735]);

add_block('simulink/Math Operations/Sum', ...
    [model '/External Return Temperature C'], ...
    'Inputs', '++', ...
    'Position', [1130 660 1180 730]);

add_line(model, 'External Mass Flow kg_s/1', ...
    'External mDot x cp/1', 'autorouting', 'on');
add_line(model, 'External cp/1', ...
    'External mDot x cp/2', 'autorouting', 'on');
add_line(model, 'External Heat W/1', ...
    'External Actual DeltaT K/1', 'autorouting', 'on');
add_line(model, 'External mDot x cp/1', ...
    'External Actual DeltaT K/2', 'autorouting', 'on');
add_line(model, 'External Supply Temperature C/1', ...
    'External Return Temperature C/1', 'autorouting', 'on');
add_line(model, 'External Actual DeltaT K/1', ...
    'External Return Temperature C/2', 'autorouting', 'on');

%% 8. CLOSED-CIRCUIT COOLING TOWER / HEAT REJECTION

% External pump losses are also assumed to enter the PG25 loop.
add_block('simulink/Math Operations/Sum', ...
    [model '/Tower Heat Rejection kW'], ...
    'Inputs', '++', ...
    'Position', [1700 450 1760 515]);

add_block('simulink/Math Operations/Gain', ...
    [model '/Tower Load Ratio'], ...
    'Gain', '1/tower_design_heat_kW', ...
    'Position', [1810 460 1900 505]);

add_block('simulink/Discontinuities/Saturation', ...
    [model '/Tower Load Ratio Limited'], ...
    'UpperLimit', '1', ...
    'LowerLimit', '0', ...
    'Position', [1950 455 2025 510]);

add_block('simulink/Math Operations/Product', ...
    [model '/Tower Load Ratio Cubed'], ...
    'Inputs', '***', ...
    'Position', [2075 405 2135 475]);

add_block('simulink/Math Operations/Gain', ...
    [model '/Tower Fan Power kW'], ...
    'Gain', 'tower_fan_design_kW', ...
    'Position', [2185 410 2285 455]);

add_block('simulink/Math Operations/Gain', ...
    [model '/Tower Spray Pump Power kW'], ...
    'Gain', 'tower_spray_pump_design_kW', ...
    'Position', [2075 520 2200 565]);

add_block('simulink/Math Operations/Sum', ...
    [model '/Tower Electrical Power kW'], ...
    'Inputs', '++', ...
    'Position', [2340 450 2400 515]);

add_line(model, 'CDU Heat to External Loop kW/1', ...
    'Tower Heat Rejection kW/1', 'autorouting', 'on');
add_line(model, 'External Pump Power kW/1', ...
    'Tower Heat Rejection kW/2', 'autorouting', 'on');
add_line(model, 'Tower Heat Rejection kW/1', ...
    'Tower Load Ratio/1', 'autorouting', 'on');
add_line(model, 'Tower Load Ratio/1', ...
    'Tower Load Ratio Limited/1', 'autorouting', 'on');
add_line(model, 'Tower Load Ratio Limited/1', ...
    'Tower Load Ratio Cubed/1', 'autorouting', 'on');
add_line(model, 'Tower Load Ratio Limited/1', ...
    'Tower Load Ratio Cubed/2', 'autorouting', 'on');
add_line(model, 'Tower Load Ratio Limited/1', ...
    'Tower Load Ratio Cubed/3', 'autorouting', 'on');
add_line(model, 'Tower Load Ratio Cubed/1', ...
    'Tower Fan Power kW/1', 'autorouting', 'on');
add_line(model, 'Tower Load Ratio Limited/1', ...
    'Tower Spray Pump Power kW/1', 'autorouting', 'on');
add_line(model, 'Tower Fan Power kW/1', ...
    'Tower Electrical Power kW/1', 'autorouting', 'on');
add_line(model, 'Tower Spray Pump Power kW/1', ...
    'Tower Electrical Power kW/2', 'autorouting', 'on');

%% 9. FACILITY ELECTRICAL POWER, ENERGY, AND PUE

add_block('simulink/Sources/Constant', [model '/Auxiliary Power kW'], ...
    'Value', 'auxiliary_power_kW', ...
    'Position', [1540 790 1640 820]);

add_block('simulink/Math Operations/Sum', ...
    [model '/Total Pump Power kW'], ...
    'Inputs', '++', ...
    'Position', [1700 730 1760 795]);

add_block('simulink/Math Operations/Sum', ...
    [model '/Facility Electrical Power kW'], ...
    'Inputs', '+++++', ...
    'Position', [1830 785 1890 880]);

add_block('simulink/Math Operations/Product', [model '/PUE'], ...
    'Inputs', '*/', ...
    'Position', [1970 805 2030 865]);

add_line(model, 'Internal Pump Power kW/1', ...
    'Total Pump Power kW/1', 'autorouting', 'on');
add_line(model, 'External Pump Power kW/1', ...
    'Total Pump Power kW/2', 'autorouting', 'on');

add_line(model, 'Rack IT Power kW/1', ...
    'Facility Electrical Power kW/1', 'autorouting', 'on');
add_line(model, 'Internal Pump Power kW/1', ...
    'Facility Electrical Power kW/2', 'autorouting', 'on');
add_line(model, 'External Pump Power kW/1', ...
    'Facility Electrical Power kW/3', 'autorouting', 'on');
add_line(model, 'Tower Electrical Power kW/1', ...
    'Facility Electrical Power kW/4', 'autorouting', 'on');
add_line(model, 'Auxiliary Power kW/1', ...
    'Facility Electrical Power kW/5', 'autorouting', 'on');

add_line(model, 'Facility Electrical Power kW/1', 'PUE/1', ...
    'autorouting', 'on');
add_line(model, 'Rack IT Power kW/1', 'PUE/2', ...
    'autorouting', 'on');

% Energy integrators: kW*s divided by 3600 gives kWh
energy_signals = {
    'Facility Electrical Power kW', 'Facility Energy Integrator', ...
        'Facility Energy kWh';
    'Rack IT Power kW',             'IT Energy Integrator', ...
        'IT Energy kWh';
    'Total Pump Power kW',          'Pump Energy Integrator', ...
        'Pump Energy kWh';
    'Tower Electrical Power kW',    'Tower Energy Integrator', ...
        'Tower Energy kWh'
};

y0 = 925;
for i = 1:size(energy_signals,1)
    source_name = energy_signals{i,1};
    integrator_name = energy_signals{i,2};
    energy_name = energy_signals{i,3};
    y = y0 + (i-1)*75;

    add_block('simulink/Continuous/Integrator', ...
        [model '/' integrator_name], ...
        'InitialCondition', '0', ...
        'Position', [1830 y 1870 y+35]);

    add_block('simulink/Math Operations/Gain', ...
        [model '/' energy_name], ...
        'Gain', '1/3600', ...
        'Position', [1930 y 2020 y+35]);

    add_line(model, [source_name '/1'], [integrator_name '/1'], ...
        'autorouting', 'on');
    add_line(model, [integrator_name '/1'], [energy_name '/1'], ...
        'autorouting', 'on');
end

%% 10. OUTPUTS AND SCOPE

output_definitions = {
    'Rack IT Power kW',                'P_IT_kW';
    'Internal Flow m3_h',              'flow_internal_m3h';
    'External Flow m3_h',              'flow_external_m3h';
    'Internal Pump Power kW',          'P_internal_pump_kW';
    'External Pump Power kW',          'P_external_pump_kW';
    'Tower Electrical Power kW',       'P_tower_kW';
    'Facility Electrical Power kW',    'P_facility_kW';
    'PUE',                             'PUE_result';
    'Estimated Chip Temperature C',    'T_chip_C';
    'Internal Return Temperature C',   'T_internal_return_C';
    'External Return Temperature C',   'T_external_return_C';
    'Facility Energy kWh',             'E_facility_kWh';
    'IT Energy kWh',                   'E_IT_kWh';
    'Pump Energy kWh',                 'E_pumps_kWh';
    'Tower Energy kWh',                'E_tower_kWh'
};

x_out = 2480;
y_out = 60;
for i = 1:size(output_definitions,1)
    source_name = output_definitions{i,1};
    variable_name = output_definitions{i,2};
    y = y_out + (i-1)*55;

    add_block('simulink/Sinks/To Workspace', ...
        [model '/Output ' variable_name], ...
        'VariableName', variable_name, ...
        'SaveFormat', 'Timeseries', ...
        'Position', [x_out y x_out+130 y+30]);

    add_line(model, [source_name '/1'], ...
        ['Output ' variable_name '/1'], 'autorouting', 'on');
end

add_block('simulink/Signal Routing/Mux', [model '/Main Signal Mux'], ...
    'Inputs', '7', ...
    'Position', [2185 690 2205 830]);

add_block('simulink/Sinks/Scope', [model '/Main Scope'], ...
    'Position', [2280 730 2340 790]);

scope_sources = {
    'Rack IT Power kW';
    'Internal Pump Power kW';
    'External Pump Power kW';
    'Tower Electrical Power kW';
    'Facility Electrical Power kW';
    'PUE';
    'Estimated Chip Temperature C'
};

for i = 1:numel(scope_sources)
    add_line(model, [scope_sources{i} '/1'], ...
        ['Main Signal Mux/' num2str(i)], 'autorouting', 'on');
end
add_line(model, 'Main Signal Mux/1', 'Main Scope/1', ...
    'autorouting', 'on');

%% 11. SAVE

save_system(model);
open_system(model);

fprintf('\nCreated %s.slx successfully.\n', model);
fprintf('Run it with the Simulink Run button or:\n');
fprintf('  simOut = sim(''%s'');\n\n', model);
fprintf('At 100%% load, the rack IT power is %.1f kW.\n', ...
    rack_design_power_kW);
fprintf(['Thermal conductivity is stored as a parameter but is not yet ' ...
    'used independently because Rth is treated as the total ' ...
    'chip-to-bulk-fluid resistance.\n']);
