function [yearly_cashflow, milestone_summary, summary] = calculate_tco( ...
    annual_facility_energy_kWh, annual_cooling_energy_kWh, p)
%CALCULATE_TCO Calculate nominal and discounted data-center cooling TCO.
%
% Facility TCO includes all facility electricity, including IT energy.
% Cooling TCO includes cooling electricity only, plus the cooling-loop
% CAPEX, fluid, maintenance, replacement, and disposal costs.
%
% Costs are assumed to occur at the end of each operating year. Initial
% CAPEX and initial fluid fill occur at Year 0.

arguments
    annual_facility_energy_kWh (1,1) double {mustBeNonnegative}
    annual_cooling_energy_kWh (1,1) double {mustBeNonnegative}
    p struct
end

N = p.analysis_horizon_years;
years = (0:N)';
operating_years = (1:N)';

% Year 0 initialization.
electricity_price = zeros(N+1,1);
facility_electricity_cost = zeros(N+1,1);
cooling_electricity_cost = zeros(N+1,1);
makeup_volume_L = zeros(N+1,1);
makeup_cost = zeros(N+1,1);
maintenance_cost = zeros(N+1,1);
replacement_event = false(N+1,1);
replacement_fluid_cost = zeros(N+1,1);
disposal_cost = zeros(N+1,1);
initial_capex = zeros(N+1,1);
discount_factor = ones(N+1,1);

initial_capex(1) = p.initial_cooling_CAPEX;

% Operating-year cash flows.
electricity_price(2:end) = p.electricity_price_year1_per_kWh .* ...
    (1+p.electricity_price_escalation_annual).^(operating_years-1);
general_cost_factor = ...
    (1+p.fluid_general_cost_escalation_annual).^(operating_years-1);
discount_factor(2:end) = 1 ./ ...
    (1+p.discount_rate_annual).^operating_years;

facility_electricity_cost(2:end) = ...
    annual_facility_energy_kWh .* electricity_price(2:end);
cooling_electricity_cost(2:end) = ...
    annual_cooling_energy_kWh .* electricity_price(2:end);

makeup_volume_L(2:end) = p.annual_makeup_volume_L;
makeup_cost(2:end) = p.annual_makeup_volume_L .* ...
    p.fluid_unit_price_year1_per_L .* general_cost_factor;
maintenance_cost(2:end) = p.annual_maintenance_monitoring_year1 .* ...
    general_cost_factor;

replacement_event(2:end) = ...
    mod(operating_years, p.full_replacement_interval_years) == 0;
replacement_fluid_cost(2:end) = replacement_event(2:end) .* ...
    p.total_loop_fluid_volume_L .* p.fluid_unit_price_year1_per_L .* ...
    general_cost_factor;
disposal_cost(2:end) = replacement_event(2:end) .* ...
    p.disposal_cost_per_full_drain_year1 .* general_cost_factor;

nonenergy_opex = makeup_cost + maintenance_cost + ...
    replacement_fluid_cost + disposal_cost;

nominal_facility_cashflow = initial_capex + ...
    facility_electricity_cost + nonenergy_opex;
nominal_cooling_cashflow = initial_capex + ...
    cooling_electricity_cost + nonenergy_opex;

discounted_facility_cashflow = nominal_facility_cashflow .* discount_factor;
discounted_cooling_cashflow = nominal_cooling_cashflow .* discount_factor;
discounted_facility_electricity = ...
    facility_electricity_cost .* discount_factor;
discounted_cooling_electricity = ...
    cooling_electricity_cost .* discount_factor;
discounted_nonenergy_opex = nonenergy_opex .* discount_factor;

cumulative_nominal_facility_TCO = cumsum(nominal_facility_cashflow);
cumulative_discounted_facility_TCO = cumsum(discounted_facility_cashflow);
cumulative_nominal_cooling_TCO = cumsum(nominal_cooling_cashflow);
cumulative_discounted_cooling_TCO = cumsum(discounted_cooling_cashflow);

yearly_cashflow = table( ...
    years, electricity_price, ...
    repmat(annual_facility_energy_kWh,N+1,1), ...
    repmat(annual_cooling_energy_kWh,N+1,1), ...
    facility_electricity_cost, cooling_electricity_cost, ...
    makeup_volume_L, makeup_cost, maintenance_cost, replacement_event, ...
    replacement_fluid_cost, disposal_cost, nonenergy_opex, initial_capex, ...
    discount_factor, discounted_facility_electricity, ...
    discounted_cooling_electricity, discounted_nonenergy_opex, ...
    cumulative_nominal_facility_TCO, ...
    cumulative_discounted_facility_TCO, ...
    cumulative_nominal_cooling_TCO, ...
    cumulative_discounted_cooling_TCO, ...
    'VariableNames', { ...
    'Year','ElectricityPrice_per_kWh', ...
    'AnnualFacilityEnergy_kWh','AnnualCoolingEnergy_kWh', ...
    'FacilityElectricityCost','CoolingElectricityCost', ...
    'MakeupVolume_L','MakeupCost','MaintenanceCost','ReplacementEvent', ...
    'ReplacementFluidCost','DisposalCost','NonEnergyOPEX','InitialCAPEX', ...
    'DiscountFactor','DiscountedFacilityElectricity', ...
    'DiscountedCoolingElectricity','DiscountedNonEnergyOPEX', ...
    'CumulativeNominalFacilityTCO','CumulativeDiscountedFacilityTCO', ...
    'CumulativeNominalCoolingTCO','CumulativeDiscountedCoolingTCO'});

reporting_years = unique(p.tco_reporting_years(:));
reporting_years = reporting_years( ...
    reporting_years >= 0 & reporting_years <= N & ...
    mod(reporting_years,1) == 0);
rows = reporting_years + 1;

milestone_summary = table( ...
    reporting_years, ...
    cumulative_nominal_facility_TCO(rows), ...
    cumulative_discounted_facility_TCO(rows), ...
    cumulative_nominal_cooling_TCO(rows), ...
    cumulative_discounted_cooling_TCO(rows), ...
    'VariableNames', {'Year','NominalFacilityTCO', ...
    'DiscountedFacilityTCO','NominalCoolingTCO','DiscountedCoolingTCO'});

summary = struct();
summary.analysis_horizon_years = N;
summary.annual_facility_energy_kWh = annual_facility_energy_kWh;
summary.annual_cooling_energy_kWh = annual_cooling_energy_kWh;
summary.initial_cooling_CAPEX = p.initial_cooling_CAPEX;
summary.nominal_facility_TCO = cumulative_nominal_facility_TCO(end);
summary.discounted_facility_TCO = cumulative_discounted_facility_TCO(end);
summary.nominal_cooling_TCO = cumulative_nominal_cooling_TCO(end);
summary.discounted_cooling_TCO = cumulative_discounted_cooling_TCO(end);
summary.discounted_facility_electricity = ...
    sum(discounted_facility_electricity);
summary.discounted_cooling_electricity = ...
    sum(discounted_cooling_electricity);
summary.discounted_nonenergy_opex = sum(discounted_nonenergy_opex);
summary.full_replacement_events = nnz(replacement_event);
end
