%% Derived model parameters
% Requires config/default_parameters.m to have been run first.

%% Validation
validateattributes(facility_IT_load_kW, {'numeric'}, {'scalar','positive'});
validateattributes(design_deltaT_K, {'numeric'}, {'scalar','positive'});
validateattributes(analysis_horizon_years, {'numeric'}, ...
    {'scalar','integer','positive'});
validateattributes(operating_hours_per_year, {'numeric'}, ...
    {'scalar','positive','<=',8784});
validateattributes(electricity_price_year1_per_kWh, {'numeric'}, ...
    {'scalar','>=',0});
validateattributes(air_void_fraction_internal, {'numeric'}, ...
    {'scalar','>=',0,'<',0.30});
validateattributes(air_void_fraction_external, {'numeric'}, ...
    {'scalar','>=',0,'<',0.30});
validateattributes(full_replacement_interval_years, {'numeric'}, ...
    {'scalar','integer','positive'});

efficiency_values = [internal_pump_efficiency external_pump_efficiency ...
    internal_motor_efficiency external_motor_efficiency ...
    internal_vfd_efficiency external_vfd_efficiency];
validateattributes(efficiency_values, {'numeric'}, ...
    {'vector','positive','<=',1});

%% Fluid-unit conversion
% 1 cP = 1e-3 Pa.s. Kinematic viscosity in cSt is derived for reporting.
mu_internal_Pas = dynamic_viscosity_internal_cP * 1e-3;
mu_external_Pas = dynamic_viscosity_external_cP * 1e-3;
nu_internal_cSt = mu_internal_Pas / rho_internal_kg_m3 * 1e6;
nu_external_cSt = mu_external_Pas / rho_external_kg_m3 * 1e6;

% Reference viscosities represent the clean PG25 case. The Excel pumping
% multiplier is retained for comparison reporting only.
mu_internal_reference_Pas = mu_internal_Pas;
mu_external_reference_Pas = mu_external_Pas;

%% Effective free-gas mixture properties
rhoCp_internal_liquid_J_m3K = rho_internal_kg_m3 * cp_internal_J_kgK;
rhoCp_external_liquid_J_m3K = rho_external_kg_m3 * cp_external_J_kgK;

rhoCp_internal_effective_J_m3K = ...
    (1-air_void_fraction_internal) * rhoCp_internal_liquid_J_m3K + ...
    air_void_fraction_internal * rho_air_kg_m3 * cp_air_J_kgK;

rho_internal_effective_kg_m3 = ...
    (1-air_void_fraction_internal) * rho_internal_kg_m3 + ...
    air_void_fraction_internal * rho_air_kg_m3;

rhoCp_external_effective_J_m3K = ...
    (1-air_void_fraction_external) * rhoCp_external_liquid_J_m3K + ...
    air_void_fraction_external * rho_air_kg_m3 * cp_air_J_kgK;

rho_external_effective_kg_m3 = ...
    (1-air_void_fraction_external) * rho_external_kg_m3 + ...
    air_void_fraction_external * rho_air_kg_m3;

% At constant useful liquid flow, the pump must transport the liquid plus the
% free-gas volume. These factors convert liquid flow into pump mixture flow.
internal_mixture_flow_factor = 1 / (1-air_void_fraction_internal);
external_mixture_flow_factor = 1 / (1-air_void_fraction_external);

%% Aeration derating
internal_pump_efficiency_ratio = max( ...
    minimum_pump_efficiency_fraction, ...
    1-internal_efficiency_derating_coefficient*air_void_fraction_internal);
external_pump_efficiency_ratio = max( ...
    minimum_pump_efficiency_fraction, ...
    1-external_efficiency_derating_coefficient*air_void_fraction_external);

internal_pump_efficiency_effective = ...
    internal_pump_efficiency * internal_pump_efficiency_ratio;
external_pump_efficiency_effective = ...
    external_pump_efficiency * external_pump_efficiency_ratio;

internal_two_phase_dp_multiplier = ...
    1 + internal_two_phase_dp_coefficient*air_void_fraction_internal;
external_two_phase_dp_multiplier = ...
    1 + external_two_phase_dp_coefficient*air_void_fraction_external;

% Deprecated aliases retained for compatibility with older reports.
internal_pump_flow_capacity_factor = 1 / internal_mixture_flow_factor;
external_pump_flow_capacity_factor = 1 / external_mixture_flow_factor;

Rth_chip_to_coolant_effective_K_W = Rth_chip_to_coolant_K_W * ...
    (1+Rth_aeration_sensitivity*air_void_fraction_internal);

%% Facility design point
rack_design_power_kW = rack_U * kW_per_U;
rack_count_equivalent = facility_IT_load_kW / rack_design_power_kW;
facility_design_IT_power_kW = facility_IT_load_kW;
facility_design_heat_kW = facility_design_IT_power_kW * ...
    heat_capture_fraction;
facility_total_U = facility_design_IT_power_kW / kW_per_U;
total_coldplate_paths = facility_total_U * coldplates_per_U;
internal_pipe_length_m = internal_fixed_pipe_length_m + ...
    internal_pipe_length_per_U_m * facility_total_U;
external_pipe_length_m = external_fixed_pipe_length_m + ...
    additional_external_pipe_length_per_rack_m * rack_count_equivalent;

%% Loop volume and Excel reference values
total_loop_fluid_volume_L = ...
    loop_fluid_volume_factor_L_per_kW * facility_design_IT_power_kW;
annual_makeup_volume_L = ...
    annual_makeup_loss_fraction * total_loop_fluid_volume_L;

baseline_CDU_pump_CAPEX = ...
    baseline_CDU_pump_CAPEX_per_kW_IT * facility_design_IT_power_kW;
PG25_CDU_pump_CAPEX = ...
    baseline_CDU_pump_CAPEX * CDU_pump_CAPEX_uplift_vs_water;
initial_fluid_fill_cost = ...
    total_loop_fluid_volume_L * fluid_unit_price_year1_per_L;
initial_cooling_CAPEX = PG25_CDU_pump_CAPEX + initial_fluid_fill_cost;

baseline_water_pump_power_kW = ...
    baseline_pump_power_fraction_of_IT * facility_design_IT_power_kW;
target_PG25_total_pump_power_kW = ...
    baseline_water_pump_power_kW * pumping_power_multiplier_vs_water;

%% Clean-fluid hydraulic reference values
% The reference point is always calculated at zero free-gas content.
Q_design_W = facility_design_heat_kW * 1000;
Vdot_internal_reference_m3s = Q_design_W / ...
    (rhoCp_internal_liquid_J_m3K*internal_target_deltaT_K);
Vdot_external_reference_m3s = Q_design_W / ...
    (rhoCp_external_liquid_J_m3K*external_target_deltaT_K);

% Darcy-Weisbach average-case reference pressure drops using the explicit
% Swamee-Jain turbulent friction-factor correlation.
internal_reference_velocity_m_s = 4*Vdot_internal_reference_m3s / ...
    (pi*internal_pipe_diameter_m^2);
internal_reference_Re = rho_internal_kg_m3 * internal_reference_velocity_m_s * ...
    internal_pipe_diameter_m / mu_internal_Pas;
internal_reference_friction_factor = 0.25 / ...
    log10(internal_pipe_roughness_m/(3.7*internal_pipe_diameter_m) + ...
    5.74/max(internal_reference_Re,1)^0.9)^2;
internal_reference_pressure_drop_Pa = ...
    (internal_reference_friction_factor*internal_pipe_length_m/internal_pipe_diameter_m + ...
    internal_fittings_loss_coefficient) * rho_internal_kg_m3 * ...
    internal_reference_velocity_m_s^2 / 2 + coldplate_pressure_drop_Pa;

internal_reference_branch_flow_m3s = ...
    Vdot_internal_reference_m3s / total_coldplate_paths;

external_reference_velocity_m_s = 4*Vdot_external_reference_m3s / ...
    (pi*external_pipe_diameter_m^2);
external_reference_Re = rho_external_kg_m3 * external_reference_velocity_m_s * ...
    external_pipe_diameter_m / mu_external_Pas;
external_reference_friction_factor = 0.25 / ...
    log10(external_pipe_roughness_m/(3.7*external_pipe_diameter_m) + ...
    5.74/max(external_reference_Re,1)^0.9)^2;
external_reference_pressure_drop_Pa = ...
    (external_reference_friction_factor*external_pipe_length_m/external_pipe_diameter_m + ...
    external_fittings_loss_coefficient) * rho_external_kg_m3 * ...
    external_reference_velocity_m_s^2 / 2;

internal_clean_shaft_pump_kW = internal_reference_pressure_drop_Pa * ...
    Vdot_internal_reference_m3s / (internal_pump_efficiency*1000);
internal_clean_raw_pump_kW = internal_clean_shaft_pump_kW / ...
    (internal_motor_efficiency*internal_vfd_efficiency);

% Only shaft power is added to the liquid heat load. Motor and VFD losses are
% electrical losses outside the hydraulic circuit.
external_clean_heat_kW = ...
    facility_design_heat_kW + internal_clean_shaft_pump_kW;
external_clean_flow_m3s = external_clean_heat_kW*1000 / ...
    (rhoCp_external_liquid_J_m3K*external_target_deltaT_K);
external_clean_flow_ratio = external_clean_flow_m3s / ...
    Vdot_external_reference_m3s;
external_clean_dp_Pa = external_reference_pressure_drop_Pa * ...
    external_clean_flow_ratio^2;
external_clean_shaft_pump_kW = external_clean_dp_Pa * ...
    external_clean_flow_m3s / (external_pump_efficiency*1000);
external_clean_raw_pump_kW = external_clean_shaft_pump_kW / ...
    (external_motor_efficiency*external_vfd_efficiency);

% Active pump outputs are calculated directly from hydraulic equations.
% Retain this legacy variable at unity so old reports do not break.
pump_power_calibration_factor = 1.0;
clean_calibrated_total_pump_power_kW = ...
    internal_clean_raw_pump_kW + external_clean_raw_pump_kW;

%% Actual design point with configured aeration
% Useful liquid flow remains fixed by heat duty and target delta T. Aeration
% increases the pump mixture flow by 1/(1-alpha).
Vdot_internal_design_delivered_m3s = Q_design_W / ...
    (rhoCp_internal_liquid_J_m3K*internal_target_deltaT_K);
Vdot_internal_design_pump_m3s = Vdot_internal_design_delivered_m3s * ...
    internal_mixture_flow_factor;
internal_design_flow_ratio = Vdot_internal_design_pump_m3s / ...
    Vdot_internal_reference_m3s;
internal_design_dp_Pa = internal_reference_pressure_drop_Pa * ...
    internal_design_flow_ratio^2 * ...
    (rho_internal_effective_kg_m3/rho_internal_kg_m3) * ...
    (mu_internal_Pas/mu_internal_reference_Pas)^mu_pressure_exponent * ...
    internal_two_phase_dp_multiplier;
internal_design_pump_shaft_kW = internal_design_dp_Pa * ...
    Vdot_internal_design_pump_m3s / ...
    (internal_pump_efficiency_effective*1000);
internal_design_pump_raw_kW = internal_design_pump_shaft_kW / ...
    (internal_motor_efficiency*internal_vfd_efficiency);
internal_design_pump_kW = ...
    pump_power_calibration_factor * internal_design_pump_raw_kW;

external_design_heat_kW = ...
    facility_design_heat_kW + internal_design_pump_shaft_kW;
external_design_heat_W = external_design_heat_kW*1000;
Vdot_external_design_delivered_m3s = external_design_heat_W / ...
    (rhoCp_external_liquid_J_m3K*external_target_deltaT_K);
Vdot_external_design_pump_m3s = Vdot_external_design_delivered_m3s * ...
    external_mixture_flow_factor;
external_design_flow_ratio = Vdot_external_design_pump_m3s / ...
    Vdot_external_reference_m3s;
external_design_dp_Pa = external_reference_pressure_drop_Pa * ...
    external_design_flow_ratio^2 * ...
    (rho_external_effective_kg_m3/rho_external_kg_m3) * ...
    (mu_external_Pas/mu_external_reference_Pas)^mu_pressure_exponent * ...
    external_two_phase_dp_multiplier;
external_design_pump_shaft_kW = external_design_dp_Pa * ...
    Vdot_external_design_pump_m3s / ...
    (external_pump_efficiency_effective*1000);
external_design_pump_raw_kW = external_design_pump_shaft_kW / ...
    (external_motor_efficiency*external_vfd_efficiency);
external_design_pump_kW = ...
    pump_power_calibration_factor * external_design_pump_raw_kW;
configured_total_pump_power_kW = ...
    internal_design_pump_kW + external_design_pump_kW;
tower_design_flow_m3h = Vdot_external_design_delivered_m3s*3600;

%% Simulation and annual projection factors
simulation_duration_h = simulation_time_s/3600;
projected_operating_hours = ...
    operating_months * operating_hours_per_year / 12;
projection_scale_factor = projected_operating_hours/simulation_duration_h;
annual_projection_scale_factor = ...
    operating_hours_per_year/simulation_duration_h;

%% TCO present-worth factors and fixed non-energy costs
analysis_years = (1:analysis_horizon_years)';
electricity_price_by_year = electricity_price_year1_per_kWh * ...
    (1+electricity_price_escalation_annual).^(analysis_years-1);
general_cost_factor_by_year = ...
    (1+fluid_general_cost_escalation_annual).^(analysis_years-1);

makeup_cost_by_year = annual_makeup_volume_L * ...
    fluid_unit_price_year1_per_L .* general_cost_factor_by_year;
maintenance_cost_by_year = annual_maintenance_monitoring_year1 .* ...
    general_cost_factor_by_year;
replacement_event_by_year = ...
    mod(analysis_years, full_replacement_interval_years) == 0;
replacement_fluid_cost_by_year = replacement_event_by_year .* ...
    total_loop_fluid_volume_L .* fluid_unit_price_year1_per_L .* ...
    general_cost_factor_by_year;
disposal_cost_by_year = replacement_event_by_year .* ...
    disposal_cost_per_full_drain_year1 .* general_cost_factor_by_year;

nonenergy_opex_by_year = makeup_cost_by_year + maintenance_cost_by_year + ...
    replacement_fluid_cost_by_year + disposal_cost_by_year;
nonenergy_nominal_total_horizon = sum(nonenergy_opex_by_year);

electricity_nominal_price_factor_horizon = ...
    sum(electricity_price_by_year);
general_cost_factor_horizon = sum(general_cost_factor_by_year);

%% Build summary
fprintf('\nBuilding %s\n', model);
fprintf('Facility design IT power: %.1f kW\n', facility_design_IT_power_kW);
fprintf('Equivalent 48U racks: %.3f\n', rack_count_equivalent);
fprintf('Design loop volume: %.0f L\n', total_loop_fluid_volume_L);
fprintf('PG25 viscosity: %.2f cP, %.3f cSt\n', ...
    dynamic_viscosity_external_cP, nu_external_cSt);
fprintf('Internal free gas: %.2f vol.%%\n', 100*air_void_fraction_internal);
fprintf('External free gas: %.2f vol.%%\n', 100*air_void_fraction_external);
fprintf('Effective cold-plate Rth: %.5f K/W\n', ...
    Rth_chip_to_coolant_effective_K_W);
fprintf('Legacy PG25 pump reference: %.1f kW (not used)\n', ...
    target_PG25_total_pump_power_kW);
fprintf('Clean-fluid electrical pump power: %.1f kW\n', ...
    clean_calibrated_total_pump_power_kW);
fprintf('Configured-aeration electrical pump power: %.1f kW\n', ...
    configured_total_pump_power_kW);
fprintf('Analysis horizon: %d years at %.0f h/year\n', ...
    analysis_horizon_years, operating_hours_per_year);
