%% Derived model parameters
% Requires config/default_parameters.m to have been run first.

validateattributes(air_void_fraction_internal, {'numeric'}, ...
    {'scalar', '>=', 0, '<', 0.30});
validateattributes(air_void_fraction_external, {'numeric'}, ...
    {'scalar', '>=', 0, '<', 0.30});
validateattributes(electricity_price_per_kWh, {'numeric'}, ...
    {'scalar', '>=', 0});
validateattributes(operating_months, {'numeric'}, ...
    {'scalar', '>', 0});

% Convert kinematic to dynamic viscosity.
mu_internal_Pas = nu_internal_cSt * 1e-6 * rho_internal_kg_m3;
mu_external_Pas = nu_external_cSt * 1e-6 * rho_external_kg_m3;

% Effective free-gas mixture properties.
rhoCp_internal_effective_J_m3K = ...
    (1-air_void_fraction_internal) * rho_internal_kg_m3 * ...
        cp_internal_J_kgK + ...
    air_void_fraction_internal * rho_air_kg_m3 * cp_air_J_kgK;

rho_internal_effective_kg_m3 = ...
    (1-air_void_fraction_internal) * rho_internal_kg_m3 + ...
    air_void_fraction_internal * rho_air_kg_m3;

rhoCp_external_effective_J_m3K = ...
    (1-air_void_fraction_external) * rho_external_kg_m3 * ...
        cp_external_J_kgK + ...
    air_void_fraction_external * rho_air_kg_m3 * cp_air_J_kgK;

rho_external_effective_kg_m3 = ...
    (1-air_void_fraction_external) * rho_external_kg_m3 + ...
    air_void_fraction_external * rho_air_kg_m3;

% Aeration derating.
internal_pump_flow_capacity_factor = max( ...
    minimum_pump_flow_capacity_factor, ...
    1-internal_flow_derating_coefficient*air_void_fraction_internal);
external_pump_flow_capacity_factor = max( ...
    minimum_pump_flow_capacity_factor, ...
    1-external_flow_derating_coefficient*air_void_fraction_external);

internal_pump_efficiency_effective = internal_pump_efficiency * max( ...
    minimum_pump_efficiency_fraction, ...
    1-internal_efficiency_derating_coefficient*air_void_fraction_internal);
external_pump_efficiency_effective = external_pump_efficiency * max( ...
    minimum_pump_efficiency_fraction, ...
    1-external_efficiency_derating_coefficient*air_void_fraction_external);

Rth_chip_to_coolant_effective_K_W = Rth_chip_to_coolant_K_W * ...
    (1+Rth_aeration_sensitivity*air_void_fraction_internal);

% Facility design point.
rack_design_power_kW = rack_U * kW_per_U;
facility_design_IT_power_kW = rack_count * rack_design_power_kW;
facility_design_heat_kW = facility_design_IT_power_kW * ...
    heat_capture_fraction;
total_coldplate_paths = rack_count * coldplate_paths_per_rack;

% Reference hydraulic flow values use the clean liquid properties.
Q_design_W = facility_design_heat_kW * 1000;
Vdot_internal_reference_m3s = Q_design_W / ...
    (rho_internal_kg_m3*cp_internal_J_kgK*internal_target_deltaT_K);

Vdot_internal_design_delivered_m3s = Q_design_W / ...
    (rhoCp_internal_effective_J_m3K*internal_target_deltaT_K);
Vdot_internal_design_pump_m3s = Vdot_internal_design_delivered_m3s / ...
    internal_pump_flow_capacity_factor;

internal_design_flow_ratio = Vdot_internal_design_pump_m3s / ...
    Vdot_internal_reference_m3s;
internal_design_dp_Pa = internal_reference_pressure_drop_Pa * ...
    internal_design_flow_ratio^2 * ...
    (rho_internal_effective_kg_m3/rho_internal_kg_m3) * ...
    (mu_internal_Pas/mu_internal_reference_Pas)^mu_pressure_exponent;
internal_design_pump_kW = internal_design_dp_Pa * ...
    Vdot_internal_design_pump_m3s / ...
    (internal_pump_efficiency_effective*1000);

external_design_heat_kW = facility_design_heat_kW + ...
    internal_design_pump_kW;
external_design_heat_W = external_design_heat_kW*1000;
Vdot_external_reference_m3s = external_design_heat_W / ...
    (rho_external_kg_m3*cp_external_J_kgK*external_target_deltaT_K);
Vdot_external_design_delivered_m3s = external_design_heat_W / ...
    (rhoCp_external_effective_J_m3K*external_target_deltaT_K);
Vdot_external_design_pump_m3s = Vdot_external_design_delivered_m3s / ...
    external_pump_flow_capacity_factor;
tower_design_flow_m3h = Vdot_external_design_delivered_m3s*3600;

simulation_duration_h = simulation_time_s/3600;
projected_operating_hours = operating_months*days_per_month*hours_per_day;
projection_scale_factor = projected_operating_hours/simulation_duration_h;

fprintf('\nBuilding %s\n', model);
fprintf('Facility design IT power: %.1f kW\n', facility_design_IT_power_kW);
fprintf('Internal free gas: %.2f vol.%%\n', 100*air_void_fraction_internal);
fprintf('External free gas: %.2f vol.%%\n', 100*air_void_fraction_external);
fprintf('Effective cold-plate Rth: %.5f K/W\n', ...
    Rth_chip_to_coolant_effective_K_W);
fprintf('Projected operation: %.1f h over %.1f months\n', ...
    projected_operating_hours, operating_months);
